/*
 * Shaders/embedded.cpp — AUTO-GENERATED by scripts/embed-shaders.py
 *
 * DO NOT EDIT BY HAND.  To regenerate, run:
 *   python3 scripts/embed-shaders.py
 * from the repository root.
 */
#include "embedded.h"
#include <cstring>

/* ── vertex shader sources ──────────────────────────────────────────────── */

static const char* kPassthroughVertSrc = R"glsl(
layout(location=0) in vec2 a_pos;
layout(location=1) in vec2 a_uv;
out vec2 v_uv;

void main()
{
    gl_Position = vec4(a_pos, 0.0, 1.0);
    v_uv = a_uv;
}
)glsl";

static const char* kCursorVertSrc = R"glsl(
layout(location = 0) in vec2 a_unitPos;   // unit quad corner [-1..1]
layout(location = 1) in vec4 a_xywh;      // display-pixel rect (x, y, w, h), divisor 1
layout(location = 2) in vec4 a_color;     // RGBA marker color, divisor 1
layout(location = 3) in vec4 a_params;    // (markerSize, baseFrac, animFrac, phase), divisor 1

uniform vec2 u_screenSize;               // display resolution (px)

out vec2        v_localUV;
flat out float  v_aspect;   // w/h pixel ratio — used in frag for iso-space correction
flat out vec4   v_color;
flat out vec4   v_params;

void main()
{
    vec2 px = a_xywh.xy + (a_unitPos * 0.5 + 0.5) * a_xywh.zw;
    vec2 ndc = (px / u_screenSize) * 2.0 - 1.0;
    gl_Position = vec4(ndc.x, -ndc.y, 0.0, 1.0);

    v_localUV = a_unitPos;
    v_aspect  = a_xywh.z / a_xywh.w;   // e.g. 32/40 = 0.8 for native TFTD tile
    v_color   = a_color;
    v_params  = a_params;
}
)glsl";

static const char* kGlobe_sphereVertSrc = R"glsl(
in vec2 a_pos;   // NDC [-1,+1]
in vec2 a_uv;    // unused; present so VAO layout matches other passes

uniform vec2 u_viewportSize;

out vec2 v_pixel;

void main()
{
    gl_Position = vec4(a_pos, 0.0, 1.0);
    // Convert NDC → pixel coords (0,0 = top-left, consistent with SDL)
    v_pixel = (a_pos * vec2(0.5, -0.5) + vec2(0.5, 0.5)) * u_viewportSize;
}
)glsl";

static const char* kTile_atlasVertSrc = R"glsl(
layout(location=0) in vec2  a_corner;
layout(location=1) in vec2  a_screenPos;
layout(location=2) in vec2  a_atlasUV;
layout(location=3) in float a_shade;
layout(location=4) in float a_animFrameCount;
layout(location=5) in float a_alphaMask;
layout(location=6) in float a_iso;       // iso priority [0..1]: larger = closer to camera

uniform vec2 u_screenSize;
uniform vec2 u_tilePixelSize;
uniform vec2 u_tileUVSize;

out vec2  v_uv;
out float v_shade;
out float v_animFrameCount;
out float v_alphaMask;

void main()
{
    // Phase 17.1: add 2.0px geometry overdraw (1.0px on each side) to close 
    // sub-pixel gaps. Stretch UVs slightly to match.
    vec2 overdraw = vec2(1.0);
    vec2 offset = (a_corner * 2.0 - 1.0) * overdraw;
    vec2 pixelPos = a_screenPos + a_corner * u_tilePixelSize + offset;

    // Convert to NDC [-1, +1].
    vec2 ndc = (pixelPos / u_screenSize) * 2.0 - 1.0;

    // Flip Y: SDL uses top-left origin, GL uses bottom-left.
    ndc.y = -ndc.y;

    // Iso priority → NDC z. Smaller z wins under glDepthFunc(LESS), so larger
    // iso (closer to camera) maps to smaller z and draws on top.
    float ndcZ = 1.0 - 2.0 * a_iso;
    gl_Position = vec4(ndc, ndcZ, 1.0);

    // Atlas UV: base UV offset by this corner's fraction of one tile.
    v_uv = a_atlasUV + a_corner * u_tileUVSize;

    // Pass per-instance data straight through to the fragment shader.
    v_shade          = a_shade;
    v_animFrameCount = a_animFrameCount;
    v_alphaMask      = a_alphaMask;
}
)glsl";

static const char* kTile_atlas_rgbaVertSrc = R"glsl(
layout(location=0) in vec2  a_corner;
layout(location=1) in vec2  a_screenPos;
layout(location=2) in vec2  a_atlasUV;
layout(location=3) in float a_shade;
layout(location=4) in float a_animFrameCount;
layout(location=5) in float a_alphaMask;
layout(location=6) in float a_iso;

uniform vec2 u_screenSize;
uniform vec2 u_tilePixelSize;
uniform vec2 u_tileUVSize;

out vec2  v_uv;
out vec2  v_localUV;
out float v_shade;
out float v_animFrameCount;
out float v_alphaMask;

void main()
{
    // Phase 17.1: add 4.0px geometry overdraw (2.0px on each side) to close 
    // sub-pixel gaps. We do NOT expand UVs; instead we slightly stretch the 
    // texture over the expanded quad. This prevents sampling neighbor cells 
    // in the unguttered atlas while ensuring adjacent quads overlap.
    vec2 overdraw = vec2(2.0);
    vec2 offset = (a_corner * 2.0 - 1.0) * overdraw;
    vec2 pixelPos = a_screenPos + a_corner * u_tilePixelSize + offset;

    vec2 ndc = (pixelPos / u_screenSize) * 2.0 - 1.0;
    ndc.y = -ndc.y;
    float ndcZ = 1.0 - 2.0 * a_iso;
    gl_Position = vec4(ndc, ndcZ, 1.0);

    v_uv = a_atlasUV + a_corner * u_tileUVSize;
    v_localUV        = a_corner;
    v_shade          = a_shade;
    v_animFrameCount = a_animFrameCount;
    v_alphaMask      = a_alphaMask;
}
)glsl";

static const char* kTile_blendVertSrc = R"glsl(
layout(location=0)  in vec2  a_corner;
layout(location=1)  in vec2  a_screenPos;
layout(location=2)  in vec2  a_selfUV;
layout(location=3)  in vec2  a_neighbourUV;
layout(location=4)  in vec2  a_worldPos;
layout(location=5)  in uint  a_wangMask;
layout(location=6)  in float a_shade;
layout(location=7)  in float a_alphaMask;
layout(location=8)  in float a_iso;
layout(location=9)  in float a_animFrameCount;
layout(location=10) in float a_feather;
layout(location=11) in float a_noiseScale;
layout(location=12) in float a_noiseAmp;

uniform vec2 u_screenSize;
uniform vec2 u_tilePixelSize;
uniform vec2 u_tileUVSize;

out vec2  v_uv;
out vec2  v_neighbourUV;
out vec2  v_diamondUV;
out vec2  v_worldUV;
flat out uint v_wangMask;
out float v_shade;
out float v_animFrameCount;
out float v_alphaMask;
out float v_feather;
out float v_noiseScale;
out float v_noiseAmp;

// Diamond-local projection for the floor iso diamond (§22.0.2).
// The floor diamond occupies the lower band of the cell (y ∈ [0.6,1.0] in
// tile space).  Coefficients calibrate to the actual make_diamond_mask edges:
//   d = 2.5*(p.y − 0.8)  → the diagonal slope in iso
//   u = p.x − d           → diamond "left–right" axis
//   v = p.x + d           → diamond "right–left" axis
// Both axes range ≈ [−0.5, 1.5] across the quad; cornerField bilinear mixing
// works in this range as long as corner values are at the extremes (P13).
vec2 toDiamond(vec2 p)
{
    // §25 calibration: make_diamond_mask places the floor diamond at source rows
    // 24..39 of a 40-row tile → p.y ∈ [0.6, 0.975], widest at rows 31/32, i.e.
    // centred at 0.7875 with a half-height of 0.1875 — NOT 0.8 ± 0.2. The old
    // 2.5·(p.y−0.8) mapped the BOTTOM vertex to d≈0.44 instead of 0.5, so the
    // corner field was compressed toward the bottom and the seam feathered wider
    // at the top than the bottom (the "blends on top, hard on the bottom" skew).
    // slope 1/0.1875 = 8/3 about centre 0.7875 sends all four vertices to the
    // exact unit-square corners the cornerField expects.
    float d = (8.0 / 3.0) * (p.y - 0.7875);
    return vec2(p.x - d, p.x + d);
}

void main()
{
    // Same 4px geometry overdraw as tile_atlas_rgba.vert to close sub-pixel gaps.
    vec2 overdraw = vec2(2.0);
    vec2 offset   = (a_corner * 2.0 - 1.0) * overdraw;
    vec2 pixelPos = a_screenPos + a_corner * u_tilePixelSize + offset;

    vec2 ndc = (pixelPos / u_screenSize) * 2.0 - 1.0;
    ndc.y    = -ndc.y;
    gl_Position = vec4(ndc, 1.0 - 2.0 * a_iso, 1.0);

    v_uv          = a_selfUV      + a_corner * u_tileUVSize;
    v_neighbourUV = a_neighbourUV + a_corner * u_tileUVSize;

    // Diamond-local coord for the corner field + world-anchored noise UV (P14).
    v_diamondUV = toDiamond(a_corner);
    v_worldUV   = a_worldPos + v_diamondUV;

    v_wangMask       = a_wangMask;
    v_shade          = a_shade;
    v_animFrameCount = a_animFrameCount;
    v_alphaMask      = a_alphaMask;
    v_feather        = a_feather;
    v_noiseScale     = a_noiseScale;
    v_noiseAmp       = a_noiseAmp;
}
)glsl";

/* ── fragment shader sources ─────────────────────────────────────────────── */

static const char* kColorquadFragSrc = R"glsl(
uniform vec4 u_color;
out     vec4 out_color;

void main()
{
    out_color = u_color;
}
)glsl";

static const char* kCursorFragSrc = R"glsl(
precision highp float;

in  vec2        v_localUV;
flat in float   v_aspect;    // quad w/h — corrects X so 1 iso unit = h/2 px
flat in vec4    v_color;
flat in vec4    v_params;

out vec4 fragColor;

// L1 SDF: solid diamond centred at `c` with half-size `sz` in iso space.
float sdDiamond(vec2 p, vec2 c, float sz)
{
    vec2 d = abs(p - c);
    return (d.x + d.y) - sz;
}

void main()
{
    float inv = 1.0 / v_aspect;
    vec2 p = vec2(v_localUV.x * inv, v_localUV.y);

    // ── Floor ring mode (v_params.w < -0.5) ────────────────────────────────
    // Draws an SDF ellipse ring at the iso floor level of the tile.
    // Floor center in p-space: (0, 1 - aspect/2), derived from tile geometry.
    if (v_params.w < -0.5)
    {
        float floorCY = 1.0 - v_aspect * 0.5;
        float a = inv  * 0.82;          // X semi-axis (82 % of tile half-width)
        float b = v_aspect * 0.5 * 0.82; // Y semi-axis

        // Subtle breathing animation.
        float phase = v_params.z;
        float breathe = 1.0 + 0.03 * sin(phase * 6.283185);
        a *= breathe;
        b *= breathe;

        vec2  q = p - vec2(0.0, floorCY);
        float dist = length(vec2(q.x / a, q.y / b));
        float d = (dist - 1.0) * min(a, b);

        float ringW = v_params.y;
        float mainRing = abs(d) - ringW * 0.5;

        // Outer ring (sharp edge).
        float alpha = smoothstep(0.025, -0.025, mainRing);
        // Soft holographic glow (reduced intensity).
        float glow  = smoothstep(0.20, 0.0, max(mainRing, 0.0)) * 0.35;

        // "Digital scan" sweep effect (more subtle).
        float angle = atan(q.x / a, q.y / b);
        float sweep = smoothstep(0.20, 0.0, abs(fract(angle / 6.283185 + phase * 0.35) - 0.5)) * 0.15;
        glow += sweep;

        // Interior "plasma" fill (semi-transparent holographic look, more subtle).
        float swirl = sin(angle * 3.0 - phase * 12.0) * 0.5 + 0.5;
        float vortex = smoothstep(0.0, -0.20, d) * 0.10 * swirl;
        
        // Secondary "digital pulse" ring (more integrated).
        float d3 = d + 0.12 + 0.04 * cos(angle * 2.0 + phase * 6.0);
        float pulseRing = smoothstep(0.03, -0.03, abs(d3) - 0.01) * 0.18;

        // Inner pulsing core ring.
        float d2 = d + 0.08 + 0.03 * sin(phase * 6.283185 + 0.8);
        float innerRing = abs(d2) - ringW * 0.35;
        float alpha2 = smoothstep(0.02, -0.02, innerRing) * (0.2 + 0.1 * sin(phase * 6.283185));

        alpha = clamp(alpha + alpha2 + glow + vortex + pulseRing, 0.0, 1.0);
        if (alpha < 0.01) discard;
        fragColor = vec4(v_color.rgb, v_color.a * alpha);
        return;
    }

    // ── Ring (AP gauge) mode ────────────────────────────────────────────────
    if (v_params.x < -0.01)
    {
        float innerR  = -v_params.x;          // inner radius in iso units
        float ringW   =  v_params.y;           // ring width in iso units
        float arcFrac =  v_params.z;           // [0..1] fraction of TU remaining

        float r    = length(p);
        float ring = abs(r - (innerR + ringW * 0.5)) - ringW * 0.5;

        // Angle: 0 = top (12 o'clock), increasing clockwise.
        // atan(x, -y): at top p=(0,-1) → atan(0,1)=0; at right p=(inv,0) → π/2.
        float angle     = atan(p.x, -p.y);
        float normAngle = mod(angle / 6.28318530718 + 1.0, 1.0);

        // Faint background ring (full circle — shows TU maximum).
        float bgAlpha  = smoothstep(0.025, -0.025, ring) * 0.18;

        // Bright arc proportional to remaining TU.
        float arcMask  = step(normAngle, arcFrac);
        float arcAlpha = smoothstep(0.025, -0.025, ring) * arcMask;
        float glow     = smoothstep(0.09, 0.0, max(ring, 0.0)) * arcMask * 0.35;

        float alpha = clamp(arcAlpha + bgAlpha + glow, 0.0, 1.0);
        if (alpha < 0.01) discard;
        fragColor = vec4(v_color.rgb, v_color.a * alpha);
        return;
    }

    // ── 4-tip marker mode ───────────────────────────────────────────────────
    float markerSize = v_params.x;
    float baseFrac   = v_params.y;
    float animFrac   = v_params.z;
    float phase      = v_params.w;

    // Animated fraction: all 4 markers move together (breathing effect).
    float frac = baseFrac + animFrac * sin(phase * 6.28318530718);

    // Marker centres in iso space — equidistant from tile centre in pixels.
    vec2 cN = vec2(0.0,       -frac);
    vec2 cS = vec2(0.0,       +frac);
    vec2 cW = vec2(-frac * inv, 0.0);
    vec2 cE = vec2(+frac * inv, 0.0);

    float d = min(min(sdDiamond(p, cN, markerSize),
                      sdDiamond(p, cS, markerSize)),
                  min(sdDiamond(p, cW, markerSize),
                      sdDiamond(p, cE, markerSize)));

    float alpha = smoothstep(0.025, -0.025, d);
    float glow  = smoothstep(0.10, 0.0, max(d, 0.0)) * 0.40;

    alpha = clamp(alpha + glow, 0.0, 1.0);
    if (alpha < 0.01) discard;
    fragColor = vec4(v_color.rgb, v_color.a * alpha);
}
)glsl";

static const char* kGlobe_sphereFragSrc = R"glsl(
in  vec2 v_pixel;
out vec4 fragColor;

uniform vec2      u_globeCenter;
uniform float     u_globeRadius;
uniform float     u_camLat;
uniform float     u_camLon;
uniform vec3      u_sunDir;
uniform float     u_time;
uniform float     u_mipLevel;

uniform sampler2D u_bathymetry;
uniform sampler2D u_diffuse;
uniform sampler2D u_night;
uniform sampler2D u_clouds;

// Rotate a view-space normal by camera (lat then lon) to world space.
// camLat: rotation around X axis (pitch south/north)
// camLon: rotation around Y axis (yaw east/west)
vec3 applyCameraRotation(vec3 n, float camLat, float camLon)
{
    // Rotate around X by camLat
    float sl = sin(camLat);  float cl = cos(camLat);
    float y1 =  cl * n.y - sl * n.z;
    float z1 =  sl * n.y + cl * n.z;
    n = vec3(n.x, y1, z1);

    // Rotate around Y by camLon
    float so = sin(camLon);  float co = cos(camLon);
    float x2 =  co * n.x + so * n.z;
    float z2 = -so * n.x + co * n.z;
    n = vec3(x2, n.y, z2);

    return n;
}

void main()
{
    // Distance from globe disk centre (pixel space)
    vec2  d = v_pixel - u_globeCenter;
    float r = length(d) / u_globeRadius;
    if (r > 1.0) discard;
    float edgeAlpha = 1.0 - smoothstep(0.985, 1.0, r);

    // Orthographic inverse: pixel → unit-sphere surface normal in view space.
    // View space matches Globe::polarToCart(): +X right, +Y down, +Z front.
    float nz      = sqrt(max(0.0, 1.0 - r * r));
    vec3  n_view  = vec3(d.x / u_globeRadius, d.y / u_globeRadius, nz);

    // Rotate to world space using camera orientation.
    vec3 n_world = applyCameraRotation(n_view, -u_camLat, u_camLon);

    // World normal → equirectangular UV.
    float lat  = asin(clamp(n_world.y, -1.0, 1.0));
    // Bias atan only at the exact pole singularity; preserves accuracy elsewhere.
    float bias = (abs(n_world.x) + abs(n_world.z) < 1e-7) ? 1e-5 : 0.0;
    float lon  = atan(n_world.x, n_world.z + bias);           // [-π, +π]
    // OXCE xcom2 globe rules use inverted latitude compared to real-world
    // equirectangular imagery (London is stored near -49°, not +51°).
    // Keep geometry/clicks in game coordinates, but sample NASA textures with
    // latitude flipped so visual land/water matches the gameplay map.
    vec2  uv  = vec2((lon + 3.14159265) / 6.28318530,        // [0, 1]
                     (1.57079633 + lat) / 3.14159265);        // [0, 1]

    // Sample all layers at the selected mip level.
    vec3  bathy  = textureLod(u_bathymetry, uv, u_mipLevel).rgb;
    vec3  diff   = textureLod(u_diffuse,    uv, u_mipLevel).rgb;
    vec3  night  = textureLod(u_night,      uv, u_mipLevel).rgb;
    // Cloud layer drifts longitudinally; GL_REPEAT handles seamless wrap.
    // One wrap is ~37 minutes: visible in play, calm enough for Geoscape.
    vec2  cloudUV = vec2(uv.x + u_time * 0.00045, uv.y);
    vec4  cloud   = textureLod(u_clouds, cloudUV, u_mipLevel);

    // Stylized TFTD composite.  Real satellite colour is too bright and
    // documentary-looking next to the low-res Geoscape UI, so keep the ocean
    // dominant and treat land as a muted overlay until a real land mask ships.
    float landWarmth = diff.r * 1.15 + diff.g * 0.85 - diff.b * 1.25;
    float landMask = smoothstep(0.10, 0.28, landWarmth);

    vec3 ocean = bathy * vec3(0.16, 0.42, 0.62) + vec3(0.00, 0.018, 0.040);
    vec3 dryLand = diff * vec3(0.48, 0.56, 0.50) + vec3(0.00, 0.015, 0.020);

    // Preserve a hint of real tropical greenery.  The mask is intentionally
    // soft: enough to make Amazon/Congo/Indonesia read green, not enough to
    // pull the globe back into raw satellite-photo colours.
    float diffMax = max(max(diff.r, diff.g), diff.b);
    float diffMin = min(min(diff.r, diff.g), diff.b);
    float diffLuma = dot(diff, vec3(0.299, 0.587, 0.114));
    float diffSat = diffMax - diffMin;
    float greenHue =
        smoothstep(-0.015, 0.070, diff.g - diff.r * 0.88) *
        smoothstep(-0.030, 0.075, diff.g - diff.b * 0.78);
    float notSnow = (1.0 - smoothstep(0.50, 0.74, diffLuma)) * smoothstep(0.045, 0.155, diffSat);
    float vegetation = landMask * greenHue * notSnow;
    vec3 greenLand = diff * vec3(0.30, 0.92, 0.50) + vec3(0.00, 0.055, 0.025);
    vec3 land = mix(dryLand, greenLand, vegetation * 0.78);
    vec3 surface = mix(ocean, land, landMask);

    // Desaturate and cool the whole globe toward TFTD's sonar/navy mood.
    float luma = dot(surface, vec3(0.299, 0.587, 0.114));
    surface = mix(vec3(luma), surface, 0.72);
    surface *= vec3(0.72, 0.92, 1.05);

    // Day / night terminator.  Keep it wider than the physical value: a
    // razor-sharp terminator looks like a black stripe at Geoscape scale.
    float sunDot   = dot(n_world, u_sunDir);
    float dayFactor = smoothstep(-0.46, 0.24, sunDot);

    // Cloud opacity comes from the WebP alpha channel.  The source cloud map is
    // very dense, so compress it hard instead of washing the globe to white.
    float cloudDensity = smoothstep(0.34, 0.96, cloud.a) * 0.24;
    vec3 cloudColor = vec3(0.66, 0.86, 0.90);

    vec3 daySide = mix(surface, cloudColor, cloudDensity * dayFactor) * (0.42 + dayFactor * 0.76);
    vec3 nightSurface = surface * vec3(0.42, 0.48, 0.56);
    vec3 nightSide = (nightSurface + vec3(0.005, 0.030, 0.055) + night * vec3(0.18, 0.62, 0.78)) * (1.0 - dayFactor);

    // Darken the limb and add a thin cyan atmospheric rim inside the disk.
    float limb = smoothstep(0.03, 0.55, nz);
    vec3 rim = vec3(0.00, 0.16, 0.20) * pow(1.0 - nz, 3.0);

    fragColor = vec4((daySide + nightSide) * (0.42 + limb * 0.58) + rim, edgeAlpha);
}
)glsl";

static const char* kTexturedFragSrc = R"glsl(
uniform sampler2D u_tex;
uniform float     u_darken;
uniform vec3      u_tint;
in      vec2      v_uv;
out     vec4      out_color;

void main()
{
    vec4 c = texture(u_tex, v_uv);
    // Unset uniform (0,0,0) means "no tint" → white, so untinted callers are
    // unaffected; tinted callers pass a non-zero colour.
    vec3 tint = all(equal(u_tint, vec3(0.0))) ? vec3(1.0) : u_tint;
    out_color = vec4(c.rgb * tint * (1.0 - u_darken), c.a);
}
)glsl";

static const char* kTile_atlasFragSrc = R"glsl(
uniform sampler2D u_atlas;
uniform sampler2D u_shadeTable;
uniform float     u_animFrame;
uniform vec2      u_tileUVSize;

in vec2  v_uv;
in float v_shade;
in float v_animFrameCount;
in float v_alphaMask;

out vec4 fragColor;

void main()
{
    // Discard tiles marked as fully transparent by the MCD opacity flag.
    if (v_alphaMask < 0.5) discard;

    // Resolve the current animation frame and offset the UV horizontally.
    float frame = floor(u_animFrame * v_animFrameCount);
    vec2 uv = v_uv + vec2(frame * u_tileUVSize.x, 0.0);

    // Sample atlas: R channel holds the palette index normalised to [0, 1].
    // Multiply by 255 and round to recover the integer index.
    float palNorm = texture(u_atlas, uv).r;

    // Palette index 0 is always transparent.
    if (palNorm < (0.5 / 255.0)) discard;

    // Undiscovered tiles (v_shade==16 from CPU side) render as opaque black.
    // ShadeTable::get returns _black (0xFF000000) for shade>=16; emulate that
    // exactly here so canopy silhouettes occlude interiors the player has not
    // discovered yet, matching painter's blit behaviour.
    if (v_shade >= 15.5)
    {
        fragColor = vec4(0.0, 0.0, 0.0, 1.0);
        return;
    }

    // Shade-table lookup using texel-centre coordinates to avoid bleed
    // between adjacent entries (both atlas and shade table use GL_NEAREST,
    // but the explicit + 0.5 guard is cheap insurance).
    float shadeU = (v_shade + 0.5) / 16.0;
    float shadeV = (palNorm * 255.0 + 0.5) / 256.0;
    vec4 shaded = texture(u_shadeTable, vec2(shadeU, shadeV));

    fragColor = vec4(shaded.rgb, shaded.a);
}
)glsl";

static const char* kTile_atlas_rgbaFragSrc = R"glsl(
uniform sampler2D u_atlas;
uniform sampler2D u_shadeCurve;  // unit 3: 16×1 night ramp (Phase 22, P5)
uniform float     u_animFrame;
uniform vec2      u_tileUVSize;

in vec2  v_uv;
in vec2  v_localUV;
in float v_shade;
in float v_animFrameCount;
in float v_alphaMask;

out vec4 fragColor;

void main()
{
    if (v_alphaMask < 0.5) discard;

    float frame = floor(u_animFrame * v_animFrameCount);
    vec2 uv = v_uv + vec2(frame * u_tileUVSize.x, 0.0);

    vec4 c = texture(u_atlas, uv);

    // A value above 1.0 in alphaMask marks a floor-like O_OBJECT layer. Its
    // source still has the ordinary diamond mask, but the material fades out
    // well inside that diamond so it dissolves into the O_FLOOR below instead
    // of painting a visible, tile-sized rhombus.
    if (v_alphaMask > 1.5)
    {
        // Map the unit quad to the 2:1 isometric diamond. Each component is
        // 0..1 inside it; edge is the distance to the nearest diamond side.
        float d = 2.5 * (v_localUV.y - 0.8);
        vec2 diamondUV = vec2(v_localUV.x - d, v_localUV.x + d);
        float edge = min(min(diamondUV.x, diamondUV.y),
                         min(1.0 - diamondUV.x, 1.0 - diamondUV.y));
        c.a *= smoothstep(0.10, 0.35, edge);
    }
    // Discard only truly-transparent texels (covers the geometry-overdraw
    // border around each cell and clamp-to-edge samples outside the mask).
    if (c.a < 0.01) discard;

    // Undiscovered tiles (v_shade==16 from CPU side) render as opaque black.
    if (v_shade >= 15.5)
    {
        fragColor = vec4(0.0, 0.0, 0.0, 1.0);
        return;
    }

    // Phase 22 (P5): luminance-ramp darkening from the palette shade table so
    // HD overlay tiles match the brightness of adjacent blend tiles at night.
    float shadeF  = texture(u_shadeCurve, vec2((v_shade + 0.5) / 16.0, 0.5)).r;
    fragColor = vec4(c.rgb * shadeF, c.a);
}
)glsl";

static const char* kTile_blendFragSrc = R"glsl(
uniform sampler2D u_atlas;       // unit 0: RGBA overlay atlas
uniform sampler2D u_noise;       // unit 2: tiling noise (GL_REPEAT)
uniform sampler2D u_shadeCurve;  // unit 3: 16×1 night ramp
uniform vec2  u_tileUVSize;
uniform float u_animFrame;

in vec2  v_uv;
in vec2  v_neighbourUV;
in vec2  v_diamondUV;
in vec2  v_worldUV;
flat in uint v_wangMask;
in float v_shade;
in float v_animFrameCount;
in float v_alphaMask;
in float v_feather;
in float v_noiseScale;
in float v_noiseAmp;

out vec4 fragColor;

// Bilinear corner field in diamond-local space.
// Returns 0 (self cell) → 1 (neighbour cell).
// Bit mapping:  NW=bit3, NE=bit2, SE=bit1, SW=bit0.
// §22.0.2 calibration (derived from Camera::convertMapToScreen — screenX=16x-16y,
// screenY=8x+8y — and computeWangMask): grid-N renders screen upper-right, W
// upper-left, E lower-right, S lower-left, so the shared Wang corners land on the
// diamond VERTICES as  NW→top  NE→right  SE→bottom  SW→left.  toDiamond maps those
// vertices to d-corners  left→(0,0) top→(1,0) bottom→(0,1) right→(1,1), giving the
// bilinear placement below (the prior nw/ne/sw/se order was rotated 90°).
float cornerField(vec2 d, uint m)
{
    float nw = float((m >> 3u) & 1u);
    float ne = float((m >> 2u) & 1u);
    float se = float((m >> 1u) & 1u);
    float sw = float( m        & 1u);
    //  d(0,0)=left=SW   d(1,0)=top=NW   d(0,1)=bottom=SE   d(1,1)=right=NE
    return mix(mix(sw, nw, d.x), mix(se, ne, d.x), d.y);
}

void main()
{
    if (v_alphaMask < 0.5) discard;

    float frame    = floor(u_animFrame * v_animFrameCount);
    vec2  frameOff = vec2(frame * u_tileUVSize.x, 0.0);

    vec4 self = texture(u_atlas, v_uv          + frameOff);
    vec4 nbr  = texture(u_atlas, v_neighbourUV + frameOff);

    float fld = cornerField(v_diamondUV, v_wangMask);
    // Noise sampled at world-tile coord so it stays still under camera pan (P14).
    float nz  = texture(u_noise, v_worldUV * v_noiseScale).r - 0.5;
    // Clamp feather ≥ 0.001 to guard smoothstep UB when edge0 == edge1 (P15).
    float fe  = max(v_feather, 0.001);

    // §25 edge-localised blend. cornerField is 0.5 at a single-foreign tile's
    // CENTRE (bilinear of 1/0 corners), so smoothstep(0.5±fe, fld) smeared the mix
    // halfway across the tile and gave a bright core + wide halo that read as a
    // diamond. Remap so only the FOREIGN half (fld 0.5→1) blends: `edge` is 0
    // through the self interior and 1 at the shared seam — the tile keeps its own
    // colour at its centre and dissolves only toward the boundary.
    float edge = clamp((fld - 0.5) * 2.0, 0.0, 1.0);
    float w    = smoothstep(0.5 - fe, 0.5 + fe, edge + nz * v_noiseAmp);

    // Seam-symmetry: cap the mix at 0.5 so each tile reaches at most a 50/50 blend
    // at the seam (edge → 1 there). Both neighbours render an IDENTICAL 50/50
    // colour on the seam, so the result is independent of draw order — `baseline:
    // none` datasets (SAND) write no floor depth, so the blend pass is a pure
    // painter's-order draw, and before the cap the front tile's diamond occluded
    // the back tile's feather on one diagonal only. 0.5 is the unique cap that
    // makes the seam pixel agree from both sides (0.5·B+0.5·A == 0.5·A+0.5·B).
    vec4 c = mix(self, nbr, clamp(w, 0.0, 1.0) * 0.5);
    if (c.a < 0.01) discard;

    if (v_shade >= 15.5)
    {
        fragColor = vec4(0.0, 0.0, 0.0, 1.0);
        return;
    }
    float shadeF = texture(u_shadeCurve, vec2((v_shade + 0.5) / 16.0, 0.5)).r;
    fragColor = vec4(c.rgb * shadeF, c.a);
}
)glsl";

/* ── lookup table ───────────────────────────────────────────────────────── */

namespace OpenXcom { namespace Shaders {

struct Entry { const char* name; const char* vert; const char* frag; };

static const Entry kTable[] = {
    { "colorquad", kPassthroughVertSrc, kColorquadFragSrc },
    { "cursor", kCursorVertSrc, kCursorFragSrc },
    { "globe_sphere", kGlobe_sphereVertSrc, kGlobe_sphereFragSrc },
    { "textured", kPassthroughVertSrc, kTexturedFragSrc },
    { "tile_atlas", kTile_atlasVertSrc, kTile_atlasFragSrc },
    { "tile_atlas_rgba", kTile_atlas_rgbaVertSrc, kTile_atlas_rgbaFragSrc },
    { "tile_blend", kTile_blendVertSrc, kTile_blendFragSrc },
    { nullptr, nullptr, nullptr } /* sentinel */
};

ShaderPair findEmbedded(const char* name)
{
    if (!name) return { nullptr, nullptr };
    for (const Entry* e = kTable; e->name; ++e)
        if (strcmp(e->name, name) == 0)
            return { e->vert, e->frag };
    return { nullptr, nullptr };
}

} } // namespace OpenXcom::Shaders
