/*
 * Shaders/embedded.cpp — AUTO-GENERATED by scripts/embed-shaders.py
 *
 * DO NOT EDIT BY HAND.  To regenerate, run:
 *   python3 scripts/embed-shaders.py
 * from the repository root.
 */
#include "embedded.h"
#include <cstring>

/* ── vertex shader sources ──────────────────────────────────────────────── */

static const char* kPassthroughVertSrc = R"glsl(
in  vec2 a_pos;
in  vec2 a_uv;
out vec2 v_uv;

void main()
{
    gl_Position = vec4(a_pos, 0.0, 1.0);
    v_uv = a_uv;
}
)glsl";

static const char* kGlobe_sphereVertSrc = R"glsl(
in vec2 a_pos;   // NDC [-1,+1]
in vec2 a_uv;    // unused; present so VAO layout matches other passes

uniform vec2 u_viewportSize;

out vec2 v_pixel;

void main()
{
    gl_Position = vec4(a_pos, 0.0, 1.0);
    // Convert NDC → pixel coords (0,0 = top-left, consistent with SDL)
    v_pixel = (a_pos * vec2(0.5, -0.5) + vec2(0.5, 0.5)) * u_viewportSize;
}
)glsl";

/* ── fragment shader sources ─────────────────────────────────────────────── */

static const char* kColorquadFragSrc = R"glsl(
uniform vec4 u_color;
out     vec4 out_color;

void main()
{
    out_color = u_color;
}
)glsl";

static const char* kGlobe_sphereFragSrc = R"glsl(
in  vec2 v_pixel;
out vec4 fragColor;

uniform vec2      u_viewportSize;
uniform vec2      u_globeCenter;
uniform float     u_globeRadius;
uniform float     u_camLat;
uniform float     u_camLon;
uniform vec3      u_sunDir;
uniform float     u_time;
uniform float     u_mipLevel;

uniform sampler2D u_bathymetry;
uniform sampler2D u_diffuse;
uniform sampler2D u_night;
uniform sampler2D u_clouds;

// Rotate a view-space normal by camera (lat then lon) to world space.
// camLat: rotation around X axis (pitch south/north)
// camLon: rotation around Y axis (yaw east/west)
vec3 applyCameraRotation(vec3 n, float camLat, float camLon)
{
    // Rotate around X by camLat
    float sl = sin(camLat);  float cl = cos(camLat);
    float y1 =  cl * n.y - sl * n.z;
    float z1 =  sl * n.y + cl * n.z;
    n = vec3(n.x, y1, z1);

    // Rotate around Y by camLon
    float so = sin(camLon);  float co = cos(camLon);
    float x2 =  co * n.x + so * n.z;
    float z2 = -so * n.x + co * n.z;
    n = vec3(x2, n.y, z2);

    return n;
}

void main()
{
    // Distance from globe disk centre (pixel space)
    vec2  d = v_pixel - u_globeCenter;
    float r = length(d) / u_globeRadius;
    if (r > 1.0) discard;

    // Orthographic inverse: pixel → unit-sphere surface normal in view space.
    // View space: +X right, +Y down (SDL), +Z into screen.
    float nz      = sqrt(max(0.0, 1.0 - r * r));
    // Flip Y so north is up in world space despite SDL's down-Y convention.
    vec3  n_view  = vec3(d.x / u_globeRadius, -d.y / u_globeRadius, nz);

    // Rotate to world space using camera orientation.
    vec3 n_world = applyCameraRotation(n_view, -u_camLat, u_camLon);

    // Guard against atan(0,0) at the exact sub-solar pole.
    float nx_safe = n_world.x + 1.0e-5;
    float nz_safe = n_world.z + 1.0e-5;

    // World normal → equirectangular UV.
    float lat = asin(clamp(n_world.y, -1.0, 1.0));
    float lon = atan(nx_safe, nz_safe);                       // [-π, +π]
    vec2  uv  = vec2((lon + 3.14159265) / 6.28318530,        // [0, 1]
                     (1.57079633 - lat) / 3.14159265);        // [0, 1]

    // Sample all layers at the selected mip level.
    vec3  bathy  = textureLod(u_bathymetry, uv, u_mipLevel).rgb;
    vec3  diff   = textureLod(u_diffuse,    uv, u_mipLevel).rgb;
    vec3  night  = textureLod(u_night,      uv, u_mipLevel).rgb;
    // Cloud layer drifts longitudinally; wrap with fract for seamless repeat.
    vec2  cloudUV = vec2(fract(uv.x + u_time * 0.0001), uv.y);
    vec4  cloud   = textureLod(u_clouds, cloudUV, u_mipLevel);

    // Surface: bathymetry is the ocean base; Blue Marble dominates on land
    // where it is brighter.  Multiply diffuse slightly to keep ocean blue.
    vec3 surface = max(bathy, diff * 0.95);

    // Day / night terminator — smooth 5° (~0.087 rad) transition.
    float sunDot   = dot(n_world, u_sunDir);
    float dayFactor = smoothstep(-0.087, 0.087, sunDot);

    // Derive cloud opacity from luminance (textures are RGB JPEG, no alpha).
    float cloudDensity = dot(cloud.rgb, vec3(0.299, 0.587, 0.114));
    // Clouds invisible on the night side; render as near-white.
    vec3 daySide = mix(surface, vec3(1.0), cloudDensity * 0.9 * dayFactor);
    vec3 nightSide = night * (1.0 - dayFactor);

    fragColor = vec4(daySide + nightSide, 1.0);
}
)glsl";

static const char* kTexturedFragSrc = R"glsl(
uniform sampler2D u_tex;
in      vec2      v_uv;
out     vec4      out_color;

void main()
{
    out_color = texture(u_tex, v_uv);
}
)glsl";

/* ── lookup table ───────────────────────────────────────────────────────── */

namespace OpenXcom { namespace Shaders {

struct Entry { const char* name; const char* vert; const char* frag; };

static const Entry kTable[] = {
    { "colorquad", kPassthroughVertSrc, kColorquadFragSrc },
    { "globe_sphere", kGlobe_sphereVertSrc, kGlobe_sphereFragSrc },
    { "textured", kPassthroughVertSrc, kTexturedFragSrc },
    { nullptr, nullptr, nullptr } /* sentinel */
};

ShaderPair findEmbedded(const char* name)
{
    if (!name) return { nullptr, nullptr };
    for (const Entry* e = kTable; e->name; ++e)
        if (strcmp(e->name, name) == 0)
            return { e->vert, e->frag };
    return { nullptr, nullptr };
}

} } // namespace OpenXcom::Shaders
