#pragma once
/*
 * Shaders/embedded.h — AUTO-GENERATED by scripts/embed-shaders.py
 *
 * DO NOT EDIT BY HAND.  To regenerate, run:
 *   python3 scripts/embed-shaders.py
 * from the repository root.
 *
 * Available shader programs (use with Shader::loadFromEmbedded):
 *   "colorquad"
 *   "cursor"
 *   "emissive_glow"
 *   "globe_sphere"
 *   "hd_ui"
 *   "hd_ui_panel"
 *   "textured"
 *   "tile_atlas"
 *   "tile_atlas_rgba"
 *   "tile_blend"
 *   "underwater_grade"
 */
#include <cstring>

namespace OpenXcom { namespace Shaders {

struct ShaderPair
{
    const char* vert; /* null if not found */
    const char* frag; /* null if not found */
};

/* Look up a shader program by name. Returns {nullptr,nullptr} on miss. */
ShaderPair findEmbedded(const char* name);

} } // namespace OpenXcom::Shaders
