/*
 * Shaders/embedded.cpp — AUTO-GENERATED by scripts/embed-shaders.py
 *
 * DO NOT EDIT BY HAND.  To regenerate, run:
 *   python3 scripts/embed-shaders.py
 * from the repository root.
 */
#include "embedded.h"
#include <cstring>

/* ── vertex shader sources ──────────────────────────────────────────────── */

static const char* kPassthroughVertSrc = R"glsl(
layout(location=0) in vec2 a_pos;
layout(location=1) in vec2 a_uv;
out vec2 v_uv;

void main()
{
    gl_Position = vec4(a_pos, 0.0, 1.0);
    v_uv = a_uv;
}
)glsl";

static const char* kCursorVertSrc = R"glsl(
layout(location = 0) in vec2 a_unitPos;   // unit quad corner [-1..1]
layout(location = 1) in vec4 a_xywh;      // display-pixel rect (x, y, w, h), divisor 1
layout(location = 2) in vec4 a_color;     // RGBA outline color, divisor 1
layout(location = 3) in vec4 a_params;    // (thickness, radius, glowWidth, phase), divisor 1

uniform vec2 u_screenSize;               // display resolution (px)

out vec2       v_localUV;
flat out vec4  v_color;
flat out vec4  v_params;

void main()
{
    // Map unit corner to pixel position inside the instance rect.
    vec2 px = a_xywh.xy + (a_unitPos * 0.5 + 0.5) * a_xywh.zw;
    vec2 ndc = (px / u_screenSize) * 2.0 - 1.0;
    gl_Position = vec4(ndc.x, -ndc.y, 0.0, 1.0);

    v_localUV = a_unitPos;   // passes [-1..1] to fragment for SDF evaluation
    v_color   = a_color;
    v_params  = a_params;
}
)glsl";

static const char* kGlobe_sphereVertSrc = R"glsl(
in vec2 a_pos;   // NDC [-1,+1]
in vec2 a_uv;    // unused; present so VAO layout matches other passes

uniform vec2 u_viewportSize;

out vec2 v_pixel;

void main()
{
    gl_Position = vec4(a_pos, 0.0, 1.0);
    // Convert NDC → pixel coords (0,0 = top-left, consistent with SDL)
    v_pixel = (a_pos * vec2(0.5, -0.5) + vec2(0.5, 0.5)) * u_viewportSize;
}
)glsl";

static const char* kTile_atlasVertSrc = R"glsl(
layout(location=0) in vec2  a_corner;
layout(location=1) in vec2  a_screenPos;
layout(location=2) in vec2  a_atlasUV;
layout(location=3) in float a_shade;
layout(location=4) in float a_animFrameCount;
layout(location=5) in float a_alphaMask;
layout(location=6) in float a_iso;       // iso priority [0..1]: larger = closer to camera

uniform vec2 u_screenSize;
uniform vec2 u_tilePixelSize;
uniform vec2 u_tileUVSize;

out vec2  v_uv;
out float v_shade;
out float v_animFrameCount;
out float v_alphaMask;

void main()
{
    // Build pixel-space position of this corner within the tile.
    vec2 pixelPos = a_screenPos + a_corner * u_tilePixelSize;

    // Convert to NDC [-1, +1].
    vec2 ndc = (pixelPos / u_screenSize) * 2.0 - 1.0;

    // Flip Y: SDL uses top-left origin, GL uses bottom-left.
    ndc.y = -ndc.y;

    // Iso priority → NDC z. Smaller z wins under glDepthFunc(LESS), so larger
    // iso (closer to camera) maps to smaller z and draws on top.
    float ndcZ = 1.0 - 2.0 * a_iso;
    gl_Position = vec4(ndc, ndcZ, 1.0);

    // Atlas UV: base UV offset by this corner's fraction of one tile.
    v_uv = a_atlasUV + a_corner * u_tileUVSize;

    // Pass per-instance data straight through to the fragment shader.
    v_shade          = a_shade;
    v_animFrameCount = a_animFrameCount;
    v_alphaMask      = a_alphaMask;
}
)glsl";

static const char* kTile_atlas_rgbaVertSrc = R"glsl(
layout(location=0) in vec2  a_corner;
layout(location=1) in vec2  a_screenPos;
layout(location=2) in vec2  a_atlasUV;
layout(location=3) in float a_shade;
layout(location=4) in float a_animFrameCount;
layout(location=5) in float a_alphaMask;
layout(location=6) in float a_iso;

uniform vec2 u_screenSize;
uniform vec2 u_tilePixelSize;
uniform vec2 u_tileUVSize;

out vec2  v_uv;
out float v_shade;
out float v_animFrameCount;
out float v_alphaMask;

void main()
{
    vec2 pixelPos = a_screenPos + a_corner * u_tilePixelSize;
    vec2 ndc = (pixelPos / u_screenSize) * 2.0 - 1.0;
    ndc.y = -ndc.y;
    float ndcZ = 1.0 - 2.0 * a_iso;
    gl_Position = vec4(ndc, ndcZ, 1.0);

    v_uv = a_atlasUV + a_corner * u_tileUVSize;
    v_shade          = a_shade;
    v_animFrameCount = a_animFrameCount;
    v_alphaMask      = a_alphaMask;
}
)glsl";

/* ── fragment shader sources ─────────────────────────────────────────────── */

static const char* kColorquadFragSrc = R"glsl(
uniform vec4 u_color;
out     vec4 out_color;

void main()
{
    out_color = u_color;
}
)glsl";

static const char* kCursorFragSrc = R"glsl(
precision highp float;

in  vec2       v_localUV;
flat in vec4   v_color;
flat in vec4   v_params;   // .x thickness  .y radius  .z glowWidth  .w phase [0..1]

out vec4 fragColor;

// SDF: rounded diamond in local UV space [-1..1].
// Returns negative inside the shape, 0 on the boundary, positive outside.
float sdRoundedDiamond(vec2 p, float r)
{
    // Shrink by radius, compute L1 distance, then expand back.
    vec2 q = abs(p);
    // Normalise so that the outer diamond tip is at UV magnitude 1.
    float d = q.x + q.y - 1.0;
    // Subtract radius so corners are rounded (the SDF is clamped-rounded).
    return d - r * (1.0 - smoothstep(0.0, 0.5, max(q.x, q.y)));
}

void main()
{
    float thickness = v_params.x;
    float radius    = v_params.y;
    float glowW     = v_params.z;
    float phase     = v_params.w;   // 0..1 pulse

    float d = sdRoundedDiamond(v_localUV, radius);

    // Outline: a ring of width `thickness` centered on the SDF zero-crossing.
    // Pulse modulates the ring width so the yellow box visibly throbs.
    float t = thickness * (0.7 + 0.3 * phase);
    float outline = smoothstep(t, 0.0, abs(d));

    // Soft outer glow decays from the outer edge of the diamond.
    float glow = smoothstep(glowW, 0.0, max(d, 0.0)) * 0.4;

    float alpha = clamp(outline + glow, 0.0, 1.0);
    if (alpha < 0.01) discard;
    fragColor = vec4(v_color.rgb, v_color.a * alpha);
}
)glsl";

static const char* kGlobe_sphereFragSrc = R"glsl(
in  vec2 v_pixel;
out vec4 fragColor;

uniform vec2      u_globeCenter;
uniform float     u_globeRadius;
uniform float     u_camLat;
uniform float     u_camLon;
uniform vec3      u_sunDir;
uniform float     u_time;
uniform float     u_mipLevel;

uniform sampler2D u_bathymetry;
uniform sampler2D u_diffuse;
uniform sampler2D u_night;
uniform sampler2D u_clouds;

// Rotate a view-space normal by camera (lat then lon) to world space.
// camLat: rotation around X axis (pitch south/north)
// camLon: rotation around Y axis (yaw east/west)
vec3 applyCameraRotation(vec3 n, float camLat, float camLon)
{
    // Rotate around X by camLat
    float sl = sin(camLat);  float cl = cos(camLat);
    float y1 =  cl * n.y - sl * n.z;
    float z1 =  sl * n.y + cl * n.z;
    n = vec3(n.x, y1, z1);

    // Rotate around Y by camLon
    float so = sin(camLon);  float co = cos(camLon);
    float x2 =  co * n.x + so * n.z;
    float z2 = -so * n.x + co * n.z;
    n = vec3(x2, n.y, z2);

    return n;
}

void main()
{
    // Distance from globe disk centre (pixel space)
    vec2  d = v_pixel - u_globeCenter;
    float r = length(d) / u_globeRadius;
    if (r > 1.0) discard;
    float edgeAlpha = 1.0 - smoothstep(0.985, 1.0, r);

    // Orthographic inverse: pixel → unit-sphere surface normal in view space.
    // View space matches Globe::polarToCart(): +X right, +Y down, +Z front.
    float nz      = sqrt(max(0.0, 1.0 - r * r));
    vec3  n_view  = vec3(d.x / u_globeRadius, d.y / u_globeRadius, nz);

    // Rotate to world space using camera orientation.
    vec3 n_world = applyCameraRotation(n_view, -u_camLat, u_camLon);

    // World normal → equirectangular UV.
    float lat  = asin(clamp(n_world.y, -1.0, 1.0));
    // Bias atan only at the exact pole singularity; preserves accuracy elsewhere.
    float bias = (abs(n_world.x) + abs(n_world.z) < 1e-7) ? 1e-5 : 0.0;
    float lon  = atan(n_world.x, n_world.z + bias);           // [-π, +π]
    // OXCE xcom2 globe rules use inverted latitude compared to real-world
    // equirectangular imagery (London is stored near -49°, not +51°).
    // Keep geometry/clicks in game coordinates, but sample NASA textures with
    // latitude flipped so visual land/water matches the gameplay map.
    vec2  uv  = vec2((lon + 3.14159265) / 6.28318530,        // [0, 1]
                     (1.57079633 + lat) / 3.14159265);        // [0, 1]

    // Sample all layers at the selected mip level.
    vec3  bathy  = textureLod(u_bathymetry, uv, u_mipLevel).rgb;
    vec3  diff   = textureLod(u_diffuse,    uv, u_mipLevel).rgb;
    vec3  night  = textureLod(u_night,      uv, u_mipLevel).rgb;
    // Cloud layer drifts longitudinally; GL_REPEAT handles seamless wrap.
    // One wrap is ~37 minutes: visible in play, calm enough for Geoscape.
    vec2  cloudUV = vec2(uv.x + u_time * 0.00045, uv.y);
    vec4  cloud   = textureLod(u_clouds, cloudUV, u_mipLevel);

    // Stylized TFTD composite.  Real satellite colour is too bright and
    // documentary-looking next to the low-res Geoscape UI, so keep the ocean
    // dominant and treat land as a muted overlay until a real land mask ships.
    float landWarmth = diff.r * 1.15 + diff.g * 0.85 - diff.b * 1.25;
    float landMask = smoothstep(0.10, 0.28, landWarmth);

    vec3 ocean = bathy * vec3(0.16, 0.42, 0.62) + vec3(0.00, 0.018, 0.040);
    vec3 dryLand = diff * vec3(0.48, 0.56, 0.50) + vec3(0.00, 0.015, 0.020);

    // Preserve a hint of real tropical greenery.  The mask is intentionally
    // soft: enough to make Amazon/Congo/Indonesia read green, not enough to
    // pull the globe back into raw satellite-photo colours.
    float diffMax = max(max(diff.r, diff.g), diff.b);
    float diffMin = min(min(diff.r, diff.g), diff.b);
    float diffLuma = dot(diff, vec3(0.299, 0.587, 0.114));
    float diffSat = diffMax - diffMin;
    float greenHue =
        smoothstep(-0.015, 0.070, diff.g - diff.r * 0.88) *
        smoothstep(-0.030, 0.075, diff.g - diff.b * 0.78);
    float notSnow = (1.0 - smoothstep(0.50, 0.74, diffLuma)) * smoothstep(0.045, 0.155, diffSat);
    float vegetation = landMask * greenHue * notSnow;
    vec3 greenLand = diff * vec3(0.30, 0.92, 0.50) + vec3(0.00, 0.055, 0.025);
    vec3 land = mix(dryLand, greenLand, vegetation * 0.78);
    vec3 surface = mix(ocean, land, landMask);

    // Desaturate and cool the whole globe toward TFTD's sonar/navy mood.
    float luma = dot(surface, vec3(0.299, 0.587, 0.114));
    surface = mix(vec3(luma), surface, 0.72);
    surface *= vec3(0.72, 0.92, 1.05);

    // Day / night terminator.  Keep it wider than the physical value: a
    // razor-sharp terminator looks like a black stripe at Geoscape scale.
    float sunDot   = dot(n_world, u_sunDir);
    float dayFactor = smoothstep(-0.46, 0.24, sunDot);

    // Cloud opacity comes from the WebP alpha channel.  The source cloud map is
    // very dense, so compress it hard instead of washing the globe to white.
    float cloudDensity = smoothstep(0.34, 0.96, cloud.a) * 0.24;
    vec3 cloudColor = vec3(0.66, 0.86, 0.90);

    vec3 daySide = mix(surface, cloudColor, cloudDensity * dayFactor) * (0.42 + dayFactor * 0.76);
    vec3 nightSurface = surface * vec3(0.42, 0.48, 0.56);
    vec3 nightSide = (nightSurface + vec3(0.005, 0.030, 0.055) + night * vec3(0.18, 0.62, 0.78)) * (1.0 - dayFactor);

    // Darken the limb and add a thin cyan atmospheric rim inside the disk.
    float limb = smoothstep(0.03, 0.55, nz);
    vec3 rim = vec3(0.00, 0.16, 0.20) * pow(1.0 - nz, 3.0);

    fragColor = vec4((daySide + nightSide) * (0.42 + limb * 0.58) + rim, edgeAlpha);
}
)glsl";

static const char* kTexturedFragSrc = R"glsl(
uniform sampler2D u_tex;
uniform float     u_darken;
in      vec2      v_uv;
out     vec4      out_color;

void main()
{
    vec4 c = texture(u_tex, v_uv);
    out_color = vec4(c.rgb * (1.0 - u_darken), c.a);
}
)glsl";

static const char* kTile_atlasFragSrc = R"glsl(
uniform sampler2D u_atlas;
uniform sampler2D u_shadeTable;
uniform float     u_animFrame;
uniform vec2      u_tileUVSize;

in vec2  v_uv;
in float v_shade;
in float v_animFrameCount;
in float v_alphaMask;

out vec4 fragColor;

void main()
{
    // Discard tiles marked as fully transparent by the MCD opacity flag.
    if (v_alphaMask < 0.5) discard;

    // Resolve the current animation frame and offset the UV horizontally.
    float frame = floor(u_animFrame * v_animFrameCount);
    vec2 uv = v_uv + vec2(frame * u_tileUVSize.x, 0.0);

    // Sample atlas: R channel holds the palette index normalised to [0, 1].
    // Multiply by 255 and round to recover the integer index.
    float palNorm = texture(u_atlas, uv).r;

    // Palette index 0 is always transparent.
    if (palNorm < (0.5 / 255.0)) discard;

    // Undiscovered tiles (v_shade==16 from CPU side) render as opaque black.
    // ShadeTable::get returns _black (0xFF000000) for shade>=16; emulate that
    // exactly here so canopy silhouettes occlude interiors the player has not
    // discovered yet, matching painter's blit behaviour.
    if (v_shade >= 15.5)
    {
        fragColor = vec4(0.0, 0.0, 0.0, 1.0);
        return;
    }

    // Shade-table lookup using texel-centre coordinates to avoid bleed
    // between adjacent entries (both atlas and shade table use GL_NEAREST,
    // but the explicit + 0.5 guard is cheap insurance).
    float shadeU = (v_shade + 0.5) / 16.0;
    float shadeV = (palNorm * 255.0 + 0.5) / 256.0;
    vec4 shaded = texture(u_shadeTable, vec2(shadeU, shadeV));

    fragColor = vec4(shaded.rgb, shaded.a);
}
)glsl";

static const char* kTile_atlas_rgbaFragSrc = R"glsl(
uniform sampler2D u_atlas;
uniform float     u_animFrame;
uniform vec2      u_tileUVSize;

in vec2  v_uv;
in float v_shade;
in float v_animFrameCount;
in float v_alphaMask;

out vec4 fragColor;

void main()
{
    if (v_alphaMask < 0.5) discard;

    float frame = floor(u_animFrame * v_animFrameCount);
    vec2 uv = v_uv + vec2(frame * u_tileUVSize.x, 0.0);

    vec4 c = texture(u_atlas, uv);
    if (c.a < 0.5) discard;

    // Undiscovered tiles (v_shade==16 from CPU side) render as opaque black.
    // Matches palette path tile_atlas.frag and ShadeTable::get's _black return.
    if (v_shade >= 15.5)
    {
        fragColor = vec4(0.0, 0.0, 0.0, 1.0);
        return;
    }

    float k = 1.0 - (v_shade / 15.0) * 0.95;
    fragColor = vec4(c.rgb * k, c.a);
}
)glsl";

/* ── lookup table ───────────────────────────────────────────────────────── */

namespace OpenXcom { namespace Shaders {

struct Entry { const char* name; const char* vert; const char* frag; };

static const Entry kTable[] = {
    { "colorquad", kPassthroughVertSrc, kColorquadFragSrc },
    { "cursor", kCursorVertSrc, kCursorFragSrc },
    { "globe_sphere", kGlobe_sphereVertSrc, kGlobe_sphereFragSrc },
    { "textured", kPassthroughVertSrc, kTexturedFragSrc },
    { "tile_atlas", kTile_atlasVertSrc, kTile_atlasFragSrc },
    { "tile_atlas_rgba", kTile_atlas_rgbaVertSrc, kTile_atlas_rgbaFragSrc },
    { nullptr, nullptr, nullptr } /* sentinel */
};

ShaderPair findEmbedded(const char* name)
{
    if (!name) return { nullptr, nullptr };
    for (const Entry* e = kTable; e->name; ++e)
        if (strcmp(e->name, name) == 0)
            return { e->vert, e->frag };
    return { nullptr, nullptr };
}

} } // namespace OpenXcom::Shaders
