#!/usr/bin/env python3
"""
generate-hd-ui-contracts.py -- Phase 46.4-F33 canonical engine/DOM contract
generator (docs/phases/phase-46.4-f33-engine-dom-visual-parity.md, 46.4-F33.2).

The canonical registry at
`src/Calypso/ContractRegistry/hd-ui-contracts.json` discovers every canonical
JSON contract kept in the engine repo. Each entry produces TWO checked
consumers:

    src/Calypso/Contracts/hd-ui-theme.json     -> src/Calypso/Generated/CalypsoHdTheme.generated.h
                                                  <web-output>/hd-ui-theme.js
    src/Calypso/Contracts/f33-abandon.json -> src/Calypso/Generated/CalypsoF33Abandon.generated.h
                                              <web-output>/f33-abandon.js

Rules (normative):
  * output is DETERMINISTIC across supported build hosts (stable ordering, no
    timestamps, fixed float formatting);
  * engine paths resolve RELATIVE TO THIS SCRIPT; --web-output is relative to
    the CURRENT WORKING DIRECTORY (the parent repo root when invoked from CI);
  * --check performs no writes at all and exits 1 with a focused diff when any
    generated consumer is stale (drift detection for F33-PARITY-006);
  * the registry and contract schemas are validated before generation: unique
    source/output identities, version required, colours in
    RRGGBBAA, integer rects, explicit chamfer/content alignment rails,
    compact action targets >= 44x44, sane motion;
  * hand-editing any generated file is forbidden -- edit the JSON instead.

Run from the parent repository root:
    python3 engine/oxce/tools/generate-hd-ui-contracts.py --web-output web/public/generated
    python3 engine/oxce/tools/generate-hd-ui-contracts.py --check --web-output web/public/generated
"""

import argparse
import json
import os
import re
import sys

from hd_ui_authoring_schema import SCREEN_ID_RE, handler_matches_runtime

NL = chr(10)          # newline
TAB = chr(9)          # tab

ENGINE_TOOLS = os.path.dirname(os.path.abspath(__file__))
CALYPSO_DIR = os.path.normpath(os.path.join(ENGINE_TOOLS, "..", "src", "Calypso"))
CONTRACTS_DIR = os.path.join(CALYPSO_DIR, "Contracts")
GENERATED_DIR = os.path.join(CALYPSO_DIR, "Generated")
REGISTRY_REL = "ContractRegistry/hd-ui-contracts.json"
REGISTRY_PATH = os.path.join(CALYPSO_DIR, "ContractRegistry", "hd-ui-contracts.json")

HEADER_BANNER = "// AUTO-GENERATED by tools/generate-hd-ui-contracts.py -- DO NOT EDIT." + NL
MIN_ACTION_TARGET = 44


def fail(msg):
    print("generate-hd-ui-contracts: error: " + msg, file=sys.stderr)
    sys.exit(1)


def load_json(rel):
    path = os.path.join(CONTRACTS_DIR, rel)
    if not os.path.isfile(path):
        fail("canonical contract missing: " + path)
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


import re as _re

VERSION_RE = _re.compile(r"^[A-Za-z0-9._-]+$")


COMMAND_ACTION_COLOR_KEYS = (
    "restFillTop", "restFillBottom", "restBorder", "restGlow",
    "hoverFillTop", "hoverFillBottom", "hoverBorder", "hoverGlow",
    "pressedFillTop", "pressedFillBottom", "pressedBorder", "pressedGlow",
    "disabledFillTop", "disabledFillBottom", "disabledBorder",
    "primaryRestFillTop", "primaryRestFillBottom", "primaryRestBorder",
)
COMMAND_ACTION_GLOW_RADIUS_KEYS = ("restGlowRadiusPx", "hoverGlowRadiusPx", "pressedGlowRadiusPx")


def validate_theme(theme):
    if theme.get("schema") != 1:
        fail("hd-ui-theme.json: schema must be 1")
    if not isinstance(theme.get("version"), str) or not VERSION_RE.match(theme.get("version", "")):
        fail("hd-ui-theme.json: version string required (^[A-Za-z0-9._-]+$)")
    colors = theme.get("colors")
    if not isinstance(colors, dict) or not colors:
        fail("hd-ui-theme.json: colors object required")
    for name, value in colors.items():
        if not isinstance(value, str) or not re.fullmatch(r"[0-9A-Fa-f]{8}", value):
            fail("hd-ui-theme.json: color " + name + " must be packed RRGGBBAA")
    dlg = theme.get("dialog") or {}
    if dlg.get("radiusPx", 0) <= 0 or dlg.get("borderWidthPx", 0) <= 0:
        fail("hd-ui-theme.json: dialog.radiusPx/borderWidthPx must be > 0")
    shadow = theme.get("shadow") or {}
    halo = theme.get("halo") or {}
    if shadow.get("glowRadiusPx", 0) <= 0 or halo.get("glowRadiusPx", 0) <= 0:
        fail("hd-ui-theme.json: shadow/halo glowRadiusPx must be > 0")
    typography = theme.get("typography") or {}
    for key in ("titleFontSizeScale", "bodyFontSizeScale", "bodyLineHeight",
                "labelFontSizeScaleWide", "labelFontSizeScaleCompact",
                "bodyFontSizeScaleWide", "bodyFontSizeScaleCompact",
                "bodyFontWidthScaleWide", "bodyFontWidthScaleCompact",
                "bodyWrapMeasureScaleWide", "bodyWrapMeasureScaleCompact",
                "bodyProjectionLineHeightScaleWide", "bodyProjectionLineHeightScaleCompact"):
        if not isinstance(typography.get(key), (int, float)) or typography[key] <= 0:
            fail("hd-ui-theme.json: typography." + key + " must be > 0")
    for key in ("labelFontSizePx", "bodyFontSizePx", "titleFontWeight", "labelFontWeight", "bodyFontWeight"):
        if not isinstance(typography.get(key), int) or typography[key] <= 0:
            fail("hd-ui-theme.json: typography." + key + " must be a positive integer")
    f21_type = theme.get("f21Typography") or {}
    for key in ("protocolWidePx", "protocolCompactPx", "titleWidePx", "titleCompactPx",
                "dataWidePx", "dataCompactPx", "bodyWidePx", "bodyCompactPx",
                "inputWidePx", "inputCompactPx", "actionWidePx", "actionCompactPx"):
        if not isinstance(f21_type.get(key), int) or f21_type[key] <= 0:
            fail("hd-ui-theme.json: f21Typography." + key + " must be a positive integer")
    if (not isinstance(f21_type.get("bodyLineHeight"), (int, float))
            or f21_type["bodyLineHeight"] <= 1.0):
        fail("hd-ui-theme.json: f21Typography.bodyLineHeight must be > 1")
    f21_safe = theme.get("f21TextSafeArea") or {}
    for key in ("protocolInsetXWidePx", "protocolInsetXCompactPx",
                "protocolInsetYWidePx", "protocolInsetYCompactPx",
                "minimumHorizontalPaddingPx", "minimumVerticalPaddingPx"):
        if not isinstance(f21_safe.get(key), int) or f21_safe[key] < 4:
            fail("hd-ui-theme.json: f21TextSafeArea." + key + " must be an integer >= 4")
    command_action = theme.get("commandAction") or {}
    for key in COMMAND_ACTION_COLOR_KEYS:
        value = command_action.get(key)
        if not isinstance(value, str) or not re.fullmatch(r"[0-9A-Fa-f]{8}", value):
            fail("hd-ui-theme.json: commandAction." + key + " must be packed RRGGBBAA")
    for key in COMMAND_ACTION_GLOW_RADIUS_KEYS:
        if not isinstance(command_action.get(key), (int, float)) or command_action[key] <= 0:
            fail("hd-ui-theme.json: commandAction." + key + " must be > 0")
    if not isinstance(command_action.get("radiusPx"), (int, float)) or command_action["radiusPx"] <= 0:
        fail("hd-ui-theme.json: commandAction.radiusPx must be > 0")
    if command_action.get("hoverGlowRadiusPx", 0) <= command_action.get("restGlowRadiusPx", 1):
        fail("hd-ui-theme.json: commandAction.hoverGlowRadiusPx must read stronger than rest")
    if command_action.get("pressedGlowRadiusPx", 1) >= command_action.get("restGlowRadiusPx", 0):
        fail("hd-ui-theme.json: commandAction.pressedGlowRadiusPx must read tighter than rest")


def validate_f33(f33):
    if f33.get("schema") != 1:
        fail("f33-abandon.json: schema must be 1")
    if not isinstance(f33.get("version"), str) or not f33["version"]:
        fail("f33-abandon.json: version string required")
    form = f33.get("form") or {}
    if (form.get("id") != "f33-abandon" or form.get("familyId") != 33
            or form.get("archetype") != "small-confirmation"
            or form.get("source") != "FormConfigs/f33-abandon.json"):
        fail("f33-abandon.json: generated form identity/provenance is invalid")
    icon = form.get("icon") or {}
    if icon != {"kind": "warning", "glyph": "!", "tone": "warning"}:
        fail("f33-abandon.json: generated warning icon metadata drifted")
    buttons = form.get("buttons")
    if not isinstance(buttons, list) or len(buttons) != 2:
        fail("f33-abandon.json: generated form requires two button descriptors")
    expected_buttons = (("cancel", "KEEP PLAYING", "safe", "cancel"),
                        ("confirm", "ABANDON GAME", "danger", "confirm"))
    for button, expected in zip(buttons, expected_buttons):
        if tuple(button.get(key) for key in ("id", "label", "tone", "action")) != expected:
            fail("f33-abandon.json: generated button metadata drifted")
        button_style = button.get("style") or {}
        for key in ("fill", "border", "text"):
            if not isinstance(button_style.get(key), str) or not re.fullmatch(r"[0-9A-Fa-f]{8}", button_style[key]):
                fail("f33-abandon.json: generated button style " + key + " must be RRGGBBAA")
    copy = f33.get("copy") or {}
    for key in ("protocol", "title", "safeAction", "destructiveAction"):
        if not isinstance(copy.get(key), str) or not copy[key]:
            fail("f33-abandon.json: copy." + key + " string required")
    if (not isinstance(copy.get("message"), list) or len(copy["message"]) != 2
            or not all(isinstance(line, str) and line for line in copy["message"])):
        fail("f33-abandon.json: copy.message must contain exactly two non-empty lines")
    style = f33.get("style") or {}
    if not isinstance(style.get("cutCornerPx"), (int, float)) or style["cutCornerPx"] <= 0:
        fail("f33-abandon.json: style.cutCornerPx must be > 0")
    if (not isinstance(style.get("protocolTextInsetPx"), (int, float))
            or style["protocolTextInsetPx"] <= 0):
        fail("f33-abandon.json: style.protocolTextInsetPx must be > 0")
    if style["protocolTextInsetPx"] != style["cutCornerPx"] + 12:
        fail("f33-abandon.json: protocolTextInsetPx must be two mono cells after cutCornerPx")
    for key in ("panelFillTop", "panelFillBottom", "frame", "protocolText", "divider",
                "footerFill", "footerDot", "warning", "safeFill", "safeBorder",
                "destructiveFill", "destructiveText"):
        value = style.get(key)
        if not isinstance(value, str) or not re.fullmatch(r"[0-9A-Fa-f]{8}", value):
            fail("f33-abandon.json: style." + key + " must be packed RRGGBBAA")
    layouts = f33.get("layouts")
    if not isinstance(layouts, dict) or "wide" not in layouts or "compact" not in layouts:
        fail("f33-abandon.json: explicit wide/compact layouts required")
    for name in ("wide", "compact"):
        l = layouts[name]
        if l.get("designWidth", 0) <= 0 or l.get("designHeight", 0) <= 0:
            fail("f33-abandon.json: " + name + " design canvas required")
        for part in ("window", "status", "warning", "title", "message", "footer", "yes", "no"):
            r = l.get(part)
            if not r or not all(isinstance(r[k], int) for k in ("x", "y", "width", "height")):
                fail("f33-abandon.json: " + name + "." + part + " must be an integer rect")
        button_rects = l.get("buttons") or {}
        if set(button_rects) != {"cancel", "confirm"}:
            fail("f33-abandon.json: " + name + ".buttons must resolve cancel/confirm slots")
        if button_rects["cancel"] != l["no"] or button_rects["confirm"] != l["yes"]:
            fail("f33-abandon.json: " + name + " compatibility button aliases drifted")
        for part in ("yes", "no"):
            if l[part]["width"] < MIN_ACTION_TARGET or l[part]["height"] < MIN_ACTION_TARGET:
                fail("f33-abandon.json: " + name + "." + part
                     + " below the " + str(MIN_ACTION_TARGET) + "x" + str(MIN_ACTION_TARGET)
                     + " action-target floor")

        def contained(inner, outer):
            return (inner["x"] >= outer["x"] and inner["y"] >= outer["y"]
                    and inner["x"] + inner["width"] <= outer["x"] + outer["width"]
                    and inner["y"] + inner["height"] <= outer["y"] + outer["height"])
        if not contained(l["window"], {"x": 0, "y": 0, "width": l["designWidth"], "height": l["designHeight"]}):
            fail("f33-abandon.json: " + name + ".window must fit the design canvas")
        for part in ("status", "warning", "title", "message", "footer", "yes", "no"):
            if not contained(l[part], l["window"]):
                fail("f33-abandon.json: " + name + "." + part + " must be inside the window")
        if (l["yes"]["x"] < l["no"]["x"] + l["no"]["width"] and l["no"]["x"] < l["yes"]["x"] + l["yes"]["width"]
                and l["yes"]["y"] < l["no"]["y"] + l["no"]["height"] and l["no"]["y"] < l["yes"]["y"] + l["yes"]["height"]):
            fail("f33-abandon.json: " + name + ".yes and .no must not overlap")
        if l["yes"]["x"] + l["yes"]["width"] != l["message"]["x"] + l["message"]["width"]:
            fail("f33-abandon.json: " + name + ".yes must end at the message content rail")
    m = f33.get("motion") or {}
    if m.get("durationMs", 0) <= 0 or m.get("durationMs", 0) > 1000:
        fail("f33-abandon.json: motion.durationMs must be in (0, 1000]")
    if not (0.0 < m.get("scaleFrom", 0.0) <= 1.0):
        fail("f33-abandon.json: motion.scaleFrom must be in (0, 1]")
    if m.get("captureModeDurationMs") != 0:
        fail("f33-abandon.json: captureModeDurationMs must be 0 (deterministic captures)")


IDENT_RE = _re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
SLUG_RE = _re.compile(r"^[a-z0-9][a-z0-9-]*$")


def load_registry(path):
    if not os.path.isfile(path):
        fail("contract registry missing: " + path)
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def validate_registry(registry):
    if registry.get("schema") != 1:
        fail("hd-ui-contracts.json: schema must be 1")
    entries = registry.get("entries")
    if not isinstance(entries, list) or not entries:
        fail("hd-ui-contracts.json: non-empty entries array required")
    seen = {"id": set(), "contract": set(), "native output": set(), "browser output": set()}
    allowed_emitters = {"theme", "legacy-abandon", "family", "screen"}
    allowed_profiles = {"theme", "legacy-abandon", "family", "command-card",
                        "small-confirmation", "contact-decision", "content-block", "screen"}
    for index, entry in enumerate(entries):
        where = "hd-ui-contracts.json: entries[" + str(index) + "]"
        if not isinstance(entry, dict):
            fail(where + " must be an object")
        contract_id = entry.get("id")
        contract = entry.get("contract")
        emitter = entry.get("emitter")
        profile = entry.get("validationProfile")
        native = entry.get("native") or {}
        browser = entry.get("browser") or {}
        if not isinstance(contract_id, str) or not SLUG_RE.match(contract_id):
            fail(where + ".id must be a lower-kebab identifier")
        if not isinstance(contract, str) or not re.fullmatch(r"[a-z0-9-]+\.json", contract):
            fail(where + ".contract must be a Contracts/*.json basename")
        if emitter not in allowed_emitters or profile not in allowed_profiles:
            fail(where + " has an unsupported emitter or validationProfile")
        if ((emitter == "theme") != (profile == "theme")
                or (emitter == "legacy-abandon") != (profile == "legacy-abandon")):
            fail(where + " emitter and validationProfile are incompatible")
        if (emitter == "screen") != (profile == "screen"):
            fail(where + " screen emitter requires the screen validationProfile")
        for key in ("namespace", "prefix"):
            if not isinstance(native.get(key), str) or not IDENT_RE.match(native[key]):
                fail(where + ".native." + key + " must be a C++ identifier")
        if (not isinstance(native.get("output"), str)
                or not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*\.generated\.h", native["output"])):
            fail(where + ".native.output must be a generated header basename")
        if not isinstance(browser.get("global"), str) or not IDENT_RE.match(browser["global"]):
            fail(where + ".browser.global must be a JavaScript identifier")
        if (not isinstance(browser.get("output"), str)
                or not re.fullmatch(r"[a-z0-9-]+\.js", browser["output"])):
            fail(where + ".browser.output must be a generated JavaScript basename")
        if not isinstance(entry.get("rendererOwnership"), str) or not entry["rendererOwnership"]:
            fail(where + ".rendererOwnership must be a non-empty string")
        scenarios = entry.get("harnessScenarioIds")
        if (not isinstance(scenarios, list)
                or any(not isinstance(value, int) or isinstance(value, bool) or value <= 0
                       for value in scenarios)):
            fail(where + ".harnessScenarioIds must contain positive integer ids")
        for label, value in (("id", contract_id), ("contract", contract),
                             ("native output", native["output"]),
                             ("browser output", browser["output"])):
            if value in seen[label]:
                fail(where + " duplicates " + label + " " + value)
            seen[label].add(value)
        if "engineTextCalibration" in entry and not isinstance(entry["engineTextCalibration"], bool):
            fail(where + ".engineTextCalibration must be boolean")
    return entries


def validate_family(doc, rel, profile, engine_text_calibration=False):
    if doc.get("schema") != 1:
        fail(rel + ": schema must be 1")
    if not isinstance(doc.get("version"), str) or not VERSION_RE.match(doc.get("version", "")):
        fail(rel + ": version string required")
    if profile in {"small-confirmation", "contact-decision"}:
        form = doc.get("form") or {}
        if form.get("archetype") != profile or not form.get("id"):
            fail(rel + ": " + profile + " form identity required")
        if doc.get("style") is None or doc.get("layouts") is None:
            fail(rel + ": " + profile + " form must carry style/layouts")
        presentation = doc.get("presentation") or {}
        density = presentation.get("density")
        numerator = presentation.get("scaleNumerator")
        denominator = presentation.get("scaleDenominator")
        if density not in ("standard", "brief-acknowledgement"):
            fail(rel + ": generated density profile is invalid")
        if (not isinstance(numerator, int) or not isinstance(denominator, int)
                or numerator <= 0 or denominator <= 0):
            fail(rel + ": generated density scale must be a positive integer ratio")
        if density == "standard" and (numerator, denominator) != (1, 1):
            fail(rel + ": standard density must use scale 1/1")
        if density == "brief-acknowledgement" and (numerator, denominator) != (2, 3):
            fail(rel + ": brief acknowledgement density must use scale 2/3")
        for layout_name in ("wide", "compact"):
            layout = doc["layouts"].get(layout_name) or {}
            buttons = layout.get("buttons") or {}
            if set(buttons) != {button["id"] for button in form.get("buttons", [])}:
                fail(rel + ": " + layout_name + " generated button geometry is incomplete")
            visible_action_floor = (MIN_ACTION_TARGET * numerator + denominator // 2) // denominator
            for button_id, rect in buttons.items():
                if (rect.get("width", 0) < visible_action_floor
                        or rect.get("height", 0) < visible_action_floor):
                    fail(rel + ": " + layout_name + ".buttons." + button_id
                         + " below the density-scaled " + str(visible_action_floor) + "x"
                         + str(visible_action_floor) + " visible-action floor")
            if form.get("buttons"):
                rightmost = buttons[form["buttons"][-1]["id"]]
                message = layout.get("message") or {}
                if (rightmost["x"] + rightmost["width"]
                        != message.get("x", 0) + message.get("width", 0)):
                    fail(rel + ": " + layout_name + " rightmost action left the text rail")
        return
    if profile == "command-card":
        if doc.get("visualProfile") != "command-card-v1":
            fail(rel + ": visualProfile must be command-card-v1")
        copy = doc.get("copy")
        if not isinstance(copy, dict) or not copy:
            fail(rel + ": fixture copy object required")
        for key, value in copy.items():
            if not isinstance(value, str) or not value:
                fail(rel + ": copy." + key + " must be a non-empty string")
            if "{STRING}" in value or "{ALT}" in value:
                fail(rel + ": copy." + key + " contains legacy placeholder/control syntax")
    if profile == "content-block":
        if doc.get("visualProfile") != "content-block-v1":
            fail(rel + ": visualProfile must be content-block-v1")
        block = doc.get("block") or {}
        if (block.get("archetype") != "content-block"
                or block.get("contentKind") not in ("text", "table")):
            fail(rel + ": generated content-block identity is invalid")
        if doc.get("presentation") != {"fitFailure": "exception", "legacyFallback": False}:
            fail(rel + ": content block must fail fast without legacy fallback")
        style = doc.get("style") or {}
        for key in ("panelFillTop", "panelFillBottom", "frame", "divider", "text"):
            if not isinstance(style.get(key), str) or not re.fullmatch(r"[0-9A-Fa-f]{8}", style[key]):
                fail(rel + ": style." + key + " must be packed 8-digit RGBA")
        for key in ("cutCornerPx", "borderWidthPx"):
            if not isinstance(style.get(key), int) or isinstance(style.get(key), bool) or style[key] <= 0:
                fail(rel + ": style." + key + " must be a positive integer")
        if any(key in (doc.get("copy") or {}) for key in
               ("title", "status", "protocol", "footer", "buttons")):
            fail(rel + ": content block emitted forbidden form chrome")
        content = doc.get("content") or {}
        if content.get("kind") != block.get("contentKind"):
            fail(rel + ": content kind must match generated block identity")
        if content.get("kind") == "table":
            columns = content.get("columns")
            rows = content.get("rows")
            if (not isinstance(columns, int) or columns < 2
                    or not isinstance(rows, list) or not rows):
                fail(rel + ": table content requires rows and at least two columns")
            if any(not isinstance(row, list) or len(row) != columns
                   or any(not isinstance(cell, str) or not cell for cell in row)
                   for row in rows):
                fail(rel + ": table rows must contain equal non-empty string cells")
            cell_parts = ["cellR" + str(row + 1) + "C" + str(column + 1)
                          for row in range(len(rows)) for column in range(columns)]
            expected_parts = (["window"]
                              + ["columnDivider" + str(index)
                                 for index in range(1, columns)]
                              + ["rowDivider" + str(index)
                                 for index in range(1, len(rows))]
                              + cell_parts)
            if doc.get("parts") != expected_parts:
                fail(rel + ": table parts do not match generated rows and columns")
            expected_copy = {part: rows[row][column]
                             for row in range(len(rows))
                             for column, part in enumerate(
                                 cell_parts[row * columns:(row + 1) * columns])}
            if doc.get("copy") != expected_copy:
                fail(rel + ": table copy does not match generated cells")
        else:
            value = content.get("value")
            if not isinstance(value, str) or not value:
                fail(rel + ": plain-text content requires a non-empty value")
            if doc.get("parts") != ["window", "text"] or doc.get("copy") != {"text": value}:
                fail(rel + ": plain-text parts/copy do not match generated content")
        metrics = doc.get("metrics") or {}
        if set(metrics) != {"wide", "compact"}:
            fail(rel + ": content block metrics must cover Wide and Compact")
        for layout_name in ("wide", "compact"):
            layout_metrics = metrics[layout_name]
            if not isinstance(layout_metrics, dict):
                fail(rel + ": " + layout_name + " metrics must be an object")
            guarded = layout_metrics.get("guardedLineHeight")
            if not isinstance(guarded, int) or guarded <= 0:
                fail(rel + ": " + layout_name + " guardedLineHeight must be positive")
            if content.get("kind") == "table":
                counts = layout_metrics.get("lineCounts")
                if (not isinstance(counts, dict) or set(counts) != set(cell_parts)
                        or any(not isinstance(count, int) or count <= 0
                               for count in counts.values())):
                    fail(rel + ": " + layout_name + " lineCounts must cover every cell")
                column_widths = layout_metrics.get("columnWidths")
                if (not isinstance(column_widths, list) or len(column_widths) != columns
                        or any(not isinstance(width, int) or width <= 0
                               for width in column_widths)):
                    fail(rel + ": " + layout_name + " columnWidths must cover every column")
                alignment = layout_metrics.get("alignment")
                if (not isinstance(alignment, dict) or set(alignment) != set(cell_parts)
                        or any(value != "top-left" for value in alignment.values())):
                    fail(rel + ": " + layout_name + " every cell must be top-left aligned")
            else:
                count = layout_metrics.get("lineCount")
                if not isinstance(count, int) or count <= 0:
                    fail(rel + ": " + layout_name + " lineCount must be positive")
                if layout_metrics.get("alignment") != "top-left":
                    fail(rel + ": " + layout_name + " text must be top-left aligned")
            for metric_name in ("maxBlockWidth", "textUnitWidth"):
                value = layout_metrics.get(metric_name)
                if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
                    fail(rel + ": " + layout_name + " " + metric_name + " must be positive")
    parts = doc.get("parts")
    if not isinstance(parts, list) or not parts:
        fail(rel + ": parts list required")
    if len(set(parts)) != len(parts):
        fail(rel + ": parts must be unique")
    for p in parts:
        if not isinstance(p, str) or not IDENT_RE.match(p):
            fail(rel + ": part name must be a C identifier: " + repr(p))
    if parts[0] != "window":
        fail(rel + ": first part must be the window root")
    actions = doc.get("actions")
    if not isinstance(actions, list):
        fail(rel + ": actions list required")
    for a in actions:
        if a not in parts:
            fail(rel + ": action " + repr(a) + " must be listed in parts")
    layouts = doc.get("layouts")
    if not isinstance(layouts, dict) or "wide" not in layouts or "compact" not in layouts:
        fail(rel + ": explicit wide/compact layouts required")
    for name in ("wide", "compact"):
        l = layouts[name]
        if l.get("designWidth", 0) <= 0 or l.get("designHeight", 0) <= 0:
            fail(rel + ": " + name + " design canvas required")
        for part in parts:
            r = l.get(part)
            if not r or not all(isinstance(r[k], int) for k in ("x", "y", "width", "height")):
                fail(rel + ": " + name + "." + part + " must be an integer rect")
        for a in actions:
            r = l[a]
            if r["width"] < MIN_ACTION_TARGET or r["height"] < MIN_ACTION_TARGET:
                fail(rel + ": " + name + "." + a
                     + " below the " + str(MIN_ACTION_TARGET) + "x" + str(MIN_ACTION_TARGET)
                     + " action-target floor")

        def contained(inner, outer):
            return (inner["x"] >= outer["x"] and inner["y"] >= outer["y"]
                    and inner["x"] + inner["width"] <= outer["x"] + outer["width"]
                    and inner["y"] + inner["height"] <= outer["y"] + outer["height"])
        if not contained(l["window"], {"x": 0, "y": 0, "width": l["designWidth"], "height": l["designHeight"]}):
            fail(rel + ": " + name + ".window must fit the design canvas")
        for part in parts:
            if part != "window" and not contained(l[part], l["window"]):
                fail(rel + ": " + name + "." + part + " must be inside the window")
        for i, a1 in enumerate(actions):
            for a2 in actions[i + 1:]:
                r1, r2 = l[a1], l[a2]
                if (r1["x"] < r2["x"] + r2["width"] and r2["x"] < r1["x"] + r1["width"]
                        and r1["y"] < r2["y"] + r2["height"] and r2["y"] < r1["y"] + r1["height"]):
                    fail(rel + ": " + name + " actions " + a1 + " and " + a2 + " must not overlap")
    m = doc.get("motion") or {}
    if m.get("durationMs", 0) <= 0 or m.get("durationMs", 0) > 1000:
        fail(rel + ": motion.durationMs must be in (0, 1000]")
    if not (0.0 < m.get("scaleFrom", 0.0) <= 1.0):
        fail(rel + ": motion.scaleFrom must be in (0, 1]")
    if m.get("captureModeDurationMs") != 0:
        fail(rel + ": captureModeDurationMs must be 0 (deterministic captures)")

    if profile == "command-card":
        spacing = doc.get("spacingRules")
        if not isinstance(spacing, list) or not spacing:
            fail(rel + ": spacingRules must be a non-empty list")
        seen_ids = set()
        for rule in spacing:
            if not isinstance(rule, dict):
                fail(rel + ": each spacing rule must be an object")
            rid = rule.get("id")
            if not isinstance(rid, str) or not rid or rid in seen_ids:
                fail(rel + ": spacing rule ids must be non-empty and unique")
            seen_ids.add(rid)
            kind = rule.get("kind")
            for layout_name in ("wide", "compact"):
                minimum = rule.get(layout_name)
                if not isinstance(minimum, int) or minimum <= 0:
                    fail(rel + ": spacing " + rid + "." + layout_name + " must be a positive integer")
            if kind == "gap":
                first, second, axis = rule.get("first"), rule.get("second"), rule.get("axis")
                if first not in parts or second not in parts or axis not in ("horizontal", "vertical"):
                    fail(rel + ": gap " + rid + " must reference two parts and a supported axis")
                for layout_name in ("wide", "compact"):
                    first_rect, second_rect = layouts[layout_name][first], layouts[layout_name][second]
                    gap = (second_rect["x"] - first_rect["x"] - first_rect["width"]
                           if axis == "horizontal"
                           else second_rect["y"] - first_rect["y"] - first_rect["height"])
                    if gap < rule[layout_name]:
                        fail(rel + ": " + layout_name + " gap " + rid + " is " + str(gap)
                             + ", expected >= " + str(rule[layout_name]))
            elif kind == "inset":
                container, child, edges = rule.get("container"), rule.get("child"), rule.get("edges")
                if container not in parts or child not in parts:
                    fail(rel + ": inset " + rid + " must reference container and child parts")
                if (not isinstance(edges, list) or not edges
                        or any(edge not in ("left", "right", "top", "bottom") for edge in edges)):
                    fail(rel + ": inset " + rid + " has unsupported edges")
                for layout_name in ("wide", "compact"):
                    outer, inner = layouts[layout_name][container], layouts[layout_name][child]
                    insets = {
                        "left": inner["x"] - outer["x"],
                        "right": outer["x"] + outer["width"] - inner["x"] - inner["width"],
                        "top": inner["y"] - outer["y"],
                        "bottom": outer["y"] + outer["height"] - inner["y"] - inner["height"],
                    }
                    for edge in edges:
                        if insets[edge] < rule[layout_name]:
                            fail(rel + ": " + layout_name + " inset " + rid + "." + edge
                                 + " is " + str(insets[edge]) + ", expected >= " + str(rule[layout_name]))
            else:
                fail(rel + ": spacing " + rid + " kind must be gap or inset")

    calibration = doc.get("engineTextScale")
    if engine_text_calibration:
        if not isinstance(calibration, dict):
            fail(rel + ": engineTextScale object required")
        for role in ("title", "data", "body", "input", "action"):
            scale = calibration.get(role)
            if not isinstance(scale, (int, float)) or not (0.0 < scale <= 1.0):
                fail(rel + ": engineTextScale." + role + " must be in (0, 1]")


def validate_screen(doc, rel):
    if doc.get("schema") != 1:
        fail(rel + ": schema must be 1")
    if not isinstance(doc.get("version"), str) or not VERSION_RE.match(doc.get("version", "")):
        fail(rel + ": version string required")
    screen = doc.get("screen") or {}
    for key in ("id", "archetype", "runtime"):
        if not isinstance(screen.get(key), str) or not screen[key]:
            fail(rel + ": screen." + key + " required")
    if not SCREEN_ID_RE.fullmatch(screen["id"]):
        fail(rel + ": screen.id must be a lower-kebab identifier")
    if screen["runtime"] not in ("production", "proof-only"):
        fail(rel + ": screen.runtime must be production or proof-only")
    if screen.get("productionHook") != (screen["runtime"] == "production"):
        fail(rel + ": screen.productionHook must derive from runtime")
    coordinate_spaces = doc.get("coordinateSpaces")
    if (not isinstance(coordinate_spaces, list) or not coordinate_spaces
            or any(not isinstance(space, str) or not space for space in coordinate_spaces)
            or len(set(coordinate_spaces)) != len(coordinate_spaces)):
        fail(rel + ": coordinateSpaces must be a non-empty unique string array")
    provenance = doc.get("provenance") or {}
    for key in ("generator", "source", "screenTemplate"):
        if not isinstance(provenance.get(key), str) or not provenance[key]:
            fail(rel + ": provenance." + key + " required")
    actions = doc.get("actions")
    if not isinstance(actions, list) or not actions:
        fail(rel + ": non-empty actions array required")
    action_ids = []
    for index, action in enumerate(actions):
        if not isinstance(action, dict):
            fail(rel + ": actions[" + str(index) + "] must be an object")
        for key in ("id", "component", "slotRole"):
            if not isinstance(action.get(key), str) or not action[key]:
                fail(rel + ": actions[" + str(index) + "]." + key + " required")
        variants = action.get("variants") or []
        if variants:
            context = action.get("variantContext")
            if not isinstance(context, str) or not context:
                fail(rel + ": action " + action["id"] + " variantContext required")
            whens = []
            for candidate in variants:
                if (not isinstance(candidate, dict)
                        or set(candidate) != {"when", "labelKey", "handler"}
                        or not isinstance(candidate.get("when"), bool)
                        or not all(isinstance(candidate.get(key), str) and candidate[key]
                                   for key in ("labelKey", "handler"))):
                    fail(rel + ": action " + action["id"]
                         + " variants must contain boolean when, labelKey, handler")
                whens.append(candidate["when"])
            if len(whens) != 2 or set(whens) != {False, True}:
                fail(rel + ": action " + action["id"]
                     + " variants must contain unique exhaustive boolean branches")
        candidates = variants or [action]
        for candidate in candidates:
            if (not isinstance(candidate, dict)
                    or not isinstance(candidate.get("handler"), str)
                    or not candidate["handler"]):
                fail(rel + ": action handler required: " + action["id"])
            if not handler_matches_runtime(candidate["handler"], screen["runtime"]):
                fail(rel + ": action handler must match the "
                     + ("proof" if screen["runtime"] == "proof-only" else "production")
                     + " runtime namespace grammar: " + action["id"])
        action_ids.append(action["id"])
    if len(set(action_ids)) != len(action_ids):
        fail(rel + ": action ids must be unique")
    labels = ((doc.get("fixture") or {}).get("labels")
              if isinstance(doc.get("fixture"), dict) else None)
    if not isinstance(labels, dict):
        fail(rel + ": fixture.labels must be an object")
    action_labels = labels.get("actions")
    if not isinstance(action_labels, dict):
        fail(rel + ": fixture.labels.actions must be an object")
    for action_id in action_ids:
        label = action_labels.get(action_id)
        if not isinstance(label, str) or not label.strip():
            fail(rel + ": fixture.labels.actions missing non-empty label for " + action_id)
    fixture_copy = labels.get("copy")
    if (not isinstance(fixture_copy, dict)
            or any(not isinstance(key, str) or not key
                   or not isinstance(value, str)
                   for key, value in fixture_copy.items())):
        fail(rel + ": fixture.labels.copy must be a string map")
    layouts = doc.get("layouts")
    if not isinstance(layouts, dict) or set(layouts) != {"wide", "compact"}:
        fail(rel + ": layouts must contain exactly wide and compact")
    for layout_name in ("wide", "compact"):
        layout = layouts[layout_name]
        if not isinstance(layout, dict):
            fail(rel + ": " + layout_name + " must be an object")
        design = layout.get("designSize")
        if (not isinstance(design, list) or len(design) != 2
                or any(not isinstance(value, int) or isinstance(value, bool) or value <= 0
                       for value in design)):
            fail(rel + ": " + layout_name + ".designSize must contain positive integers")
        regions = layout.get("regions")
        if not isinstance(regions, dict):
            fail(rel + ": " + layout_name + ".regions must be an object")
        for region_id, rect in regions.items():
            if not isinstance(region_id, str) or not region_id:
                fail(rel + ": " + layout_name + ".regions requires named rectangles")
            if (not isinstance(rect, list) or len(rect) != 4
                    or any(not isinstance(value, int) or isinstance(value, bool) for value in rect)
                    or rect[2] <= 0 or rect[3] <= 0):
                fail(rel + ": " + layout_name + ".regions." + region_id
                     + " must be an integer rectangle")
        resolved = layout.get("actions")
        if not isinstance(resolved, dict) or set(resolved) != set(action_ids):
            fail(rel + ": " + layout_name + " action geometry must cover every action")
        for action_id, action_layout in resolved.items():
            if not isinstance(action_layout, dict):
                fail(rel + ": " + layout_name + ".actions." + action_id
                     + " must be an object")
            for scalar_name in ("focusOrder", "zOrder"):
                scalar = action_layout.get(scalar_name)
                if not isinstance(scalar, int) or isinstance(scalar, bool):
                    fail(rel + ": " + layout_name + ".actions." + action_id + "."
                         + scalar_name + " must be an integer")
            coordinate_space = action_layout.get("coordinateSpace")
            if coordinate_space not in coordinate_spaces:
                fail(rel + ": " + layout_name + " action " + action_id
                     + " uses unsupported coordinateSpace " + str(coordinate_space))
            for rect_name in ("visibleRect", "hitRect"):
                rect = action_layout.get(rect_name)
                if (not isinstance(rect, list) or len(rect) != 4
                        or any(not isinstance(value, int) or isinstance(value, bool) for value in rect)
                        or rect[2] <= 0 or rect[3] <= 0):
                    fail(rel + ": " + layout_name + ".actions." + action_id + "."
                         + rect_name + " must be an integer rectangle")
            hit = action_layout["hitRect"]
            if hit[2] < MIN_ACTION_TARGET or hit[3] < MIN_ACTION_TARGET:
                fail(rel + ": " + layout_name + " action " + action_id
                     + " is below the 44x44 hit-target floor")
            if coordinate_space == "screen":
                if (hit[0] < 0 or hit[1] < 0 or hit[0] + hit[2] > design[0]
                        or hit[1] + hit[3] > design[1]):
                    fail(rel + ": " + layout_name + " action " + action_id
                         + " leaves the design canvas")


def rgba_call(value):
    # Emit the packed 0xRRGGBBAA word directly: the generated header stays
    # dependency-free (no CalypsoHdUiModel.h include needed).
    return "0x%08Xu" % int(value, 16)


def emit_theme_h(theme):
    colors = theme["colors"]
    out = [HEADER_BANNER,
           "// Canonical source: src/Calypso/Contracts/hd-ui-theme.json",
           "#pragma once",
           "#include <cstdint>",
           "#include <cstring>",
           "namespace OpenXcom { namespace Calypso { namespace CalypsoHdThemeGen {",
           'inline constexpr const char* kContractVersion = "' + theme["version"] + '";',
           "",
           "// Semantic palette (0xRRGGBBAA).",
           ]
    for name in sorted(colors.keys()):
        const = "k" + name[0].upper() + name[1:]
        out.append("inline constexpr std::uint32_t " + const + " = " + rgba_call(colors[name]) + ";")
    out.append("")
    out.append("// Style parameters (design px).")
    out.append("inline constexpr float kDialogRadiusPx = %.6ff;" % float(theme["dialog"]["radiusPx"]))
    out.append("inline constexpr float kButtonRadiusPx = %.6ff;" % float(theme["button"]["radiusPx"]))
    out.append("inline constexpr float kBorderWidthPx = %.6ff;" % float(theme["dialog"]["borderWidthPx"]))
    out.append("inline constexpr float kTitleTrackingEm = %.6ff;" % float(theme["tracking"]["titleEm"]))
    out.append("inline constexpr float kLabelTrackingEm = %.6ff;" % float(theme["tracking"]["labelEm"]))
    out.append("inline constexpr float kShadowGlowRadiusPx = %.6ff;" % float(theme["shadow"]["glowRadiusPx"]))
    out.append("inline constexpr float kHaloGlowRadiusPx = %.6ff;" % float(theme["halo"]["glowRadiusPx"]))
    out.append("inline constexpr float kTitleFontSizeScale = %.6ff;" % float(theme["typography"]["titleFontSizeScale"]))
    out.append("inline constexpr float kBodyFontSizeScale = %.6ff;" % float(theme["typography"]["bodyFontSizeScale"]))
    out.append("inline constexpr int kLabelFontSizePx = %d;" % int(theme["typography"]["labelFontSizePx"]))
    out.append("inline constexpr float kLabelFontSizeScaleWide = %.6ff;" % float(theme["typography"]["labelFontSizeScaleWide"]))
    out.append("inline constexpr float kLabelFontSizeScaleCompact = %.6ff;" % float(theme["typography"]["labelFontSizeScaleCompact"]))
    out.append("inline constexpr int kBodyFontSizePx = %d;" % int(theme["typography"]["bodyFontSizePx"]))
    out.append("inline constexpr float kBodyFontSizeScaleWide = %.6ff;" % float(theme["typography"]["bodyFontSizeScaleWide"]))
    out.append("inline constexpr float kBodyFontSizeScaleCompact = %.6ff;" % float(theme["typography"]["bodyFontSizeScaleCompact"]))
    out.append("inline constexpr float kBodyFontWidthScaleWide = %.6ff;" % float(theme["typography"]["bodyFontWidthScaleWide"]))
    out.append("inline constexpr float kBodyFontWidthScaleCompact = %.6ff;" % float(theme["typography"]["bodyFontWidthScaleCompact"]))
    out.append("inline constexpr float kBodyWrapMeasureScaleWide = %.6ff;" % float(theme["typography"]["bodyWrapMeasureScaleWide"]))
    out.append("inline constexpr float kBodyWrapMeasureScaleCompact = %.6ff;" % float(theme["typography"]["bodyWrapMeasureScaleCompact"]))
    out.append("inline constexpr float kBodyProjectionLineHeightScaleWide = %.6ff;" % float(theme["typography"]["bodyProjectionLineHeightScaleWide"]))
    out.append("inline constexpr float kBodyProjectionLineHeightScaleCompact = %.6ff;" % float(theme["typography"]["bodyProjectionLineHeightScaleCompact"]))
    out.append("inline constexpr float kBodyLineHeight = %.6ff;" % float(theme["typography"]["bodyLineHeight"]))
    out.append("inline constexpr int kTitleFontWeight = %d;" % int(theme["typography"]["titleFontWeight"]))
    out.append("inline constexpr int kLabelFontWeight = %d;" % int(theme["typography"]["labelFontWeight"]))
    out.append("inline constexpr int kBodyFontWeight = %d;" % int(theme["typography"]["bodyFontWeight"]))
    out.append("")
    out.append("// Command action styling (Geoscape HD v2 contract s.10.1): fixed")
    out.append("// canonical radius plus per-state gradient/border/glow tokens.")
    out.append("inline constexpr float kCommandActionRadiusPx = %.6ff;" % float(theme["commandAction"]["radiusPx"]))
    for key in COMMAND_ACTION_COLOR_KEYS:
        const = "kCommandAction" + key[0].upper() + key[1:]
        out.append("inline constexpr std::uint32_t " + const + " = " + rgba_call(theme["commandAction"][key]) + ";")
    for key in COMMAND_ACTION_GLOW_RADIUS_KEYS:
        const = "kCommandAction" + key[0].upper() + key[1:]
        out.append("inline constexpr float " + const + " = %.6ff;" % float(theme["commandAction"][key]))
    out.append("")
    out.append("// F21 command-card typography and hard text safe area (design px).")
    for key, value in theme["f21Typography"].items():
        name = "kF21" + key[0].upper() + key[1:]
        if key == "bodyLineHeight":
            out.append("inline constexpr float " + name + " = %.6ff;" % float(value))
        else:
            out.append("inline constexpr int " + name + " = %d;" % int(value))
    for key, value in theme["f21TextSafeArea"].items():
        out.append("inline constexpr int kF21" + key[0].upper() + key[1:] + " = %d;" % int(value))
    out.append("")
    out.append("// Semantic token key strings for the interaction-state mapping")
    out.append("// (CalypsoHdInteractionState.h) -- values above, keys here.")
    names = sorted(colors.keys())
    for name in names:
        token = "token.color." + name
        const = "kToken" + name[0].upper() + name[1:]
        out.append('inline constexpr const char* ' + const + ' = "' + token + '";')
    out.append("")
    out.append("/// Resolve a semantic token key to its packed RGBA value (0 for")
    out.append("/// unknown keys). Generated table; one source of truth.")
    out.append("inline std::uint32_t calypsoHdThemeColorForToken(const char* token)")
    out.append("{")
    out.append(TAB + "struct Entry { const char* key; std::uint32_t value; };")
    out.append(TAB + "static constexpr Entry kEntries[] = {")
    for name in names:
        const = "k" + name[0].upper() + name[1:]
        tconst = "kToken" + name[0].upper() + name[1:]
        out.append(TAB + TAB + "{ " + tconst + ", " + const + " },")
    out.append(TAB + "};")
    out.append(TAB + "for (const Entry& e : kEntries)")
    out.append(TAB + TAB + "if (std::strcmp(token, e.key) == 0) return e.value;")
    out.append(TAB + "return 0;")
    out.append("}")
    out.append("} } }")
    return NL.join(out) + NL


def f33_rect(l, part):
    r = l[part]
    return "{ " + str(r["x"]) + ", " + str(r["y"]) + ", " + str(r["width"]) + ", " + str(r["height"]) + " }"


def emit_f33_h(f33):
    layouts = f33["layouts"]
    m = f33["motion"]
    copy = f33["copy"]
    style = f33["style"]
    form = f33["form"]
    cpp_string = lambda value: json.dumps(value, ensure_ascii=False)
    out = [HEADER_BANNER,
           "// Canonical source: src/Calypso/Contracts/f33-abandon.json",
           "#pragma once",
           "#include <cstdint>",
           "namespace OpenXcom { namespace Calypso { namespace CalypsoF33AbandonGen {",
           'inline constexpr const char* kContractVersion = "' + f33["version"] + '";',
           'inline constexpr const char* kFormId = "' + form["id"] + '";',
           "inline constexpr int kFamilyId = " + str(form["familyId"]) + ";",
           'inline constexpr const char* kArchetype = "' + form["archetype"] + '";',
           'inline constexpr const char* kSourceConfig = "' + form["source"] + '";',
           "",
           "// Approved F33 3+5 copy (2026-08-17).",
           "inline constexpr const char* kProtocol = " + cpp_string(copy["protocol"]) + ";",
           "inline constexpr const char* kTitle = " + cpp_string(copy["title"]) + ";",
           "inline constexpr const char* kMessageLine1 = " + cpp_string(copy["message"][0]) + ";",
           "inline constexpr const char* kMessageLine2 = " + cpp_string(copy["message"][1]) + ";",
           "inline constexpr const char* kSafeAction = " + cpp_string(copy["safeAction"]) + ";",
           "inline constexpr const char* kDestructiveAction = " + cpp_string(copy["destructiveAction"]) + ";",
           "",
           "/// Generated semantic button descriptor; behavior stays in the logical widget.",
           "struct CalypsoF33GenButton",
           "{",
           TAB + "const char* id;",
           TAB + "const char* label;",
           TAB + "const char* tone;",
           TAB + "const char* action;",
           TAB + "std::uint32_t fill;",
           TAB + "std::uint32_t border;",
           TAB + "std::uint32_t text;",
           "};",
           "inline constexpr CalypsoF33GenButton kButtons[] =",
           "{",
           ]
    for button in form["buttons"]:
        out.append(TAB + "{ " + cpp_string(button["id"]) + ", "
                   + cpp_string(button["label"]) + ", " + cpp_string(button["tone"]) + ", "
                   + cpp_string(button["action"]) + ", " + rgba_call(button["style"]["fill"]) + ", "
                   + rgba_call(button["style"]["border"]) + ", "
                   + rgba_call(button["style"]["text"]) + " },")
    out += ["};",
           "inline constexpr int kButtonCount = " + str(len(form["buttons"])) + ";",
           "",
           "// F33-only chrome tokens (0xRRGGBBAA; design px).",
           "inline constexpr float kCutCornerPx = %.6ff;" % float(style["cutCornerPx"]),
           "inline constexpr float kProtocolTextInsetPx = %.6ff;" % float(style["protocolTextInsetPx"]),
           "inline constexpr std::uint32_t kPanelFillTop = " + rgba_call(style["panelFillTop"]) + ";",
           "inline constexpr std::uint32_t kPanelFillBottom = " + rgba_call(style["panelFillBottom"]) + ";",
           "inline constexpr std::uint32_t kFrame = " + rgba_call(style["frame"]) + ";",
           "inline constexpr std::uint32_t kProtocolText = " + rgba_call(style["protocolText"]) + ";",
           "inline constexpr std::uint32_t kDivider = " + rgba_call(style["divider"]) + ";",
           "inline constexpr std::uint32_t kFooterFill = " + rgba_call(style["footerFill"]) + ";",
           "inline constexpr std::uint32_t kFooterDot = " + rgba_call(style["footerDot"]) + ";",
           "inline constexpr std::uint32_t kWarning = " + rgba_call(style["warning"]) + ";",
           "inline constexpr std::uint32_t kSafeFill = " + rgba_call(style["safeFill"]) + ";",
           "inline constexpr std::uint32_t kSafeBorder = " + rgba_call(style["safeBorder"]) + ";",
           "inline constexpr std::uint32_t kDestructiveFill = " + rgba_call(style["destructiveFill"]) + ";",
           "inline constexpr std::uint32_t kDestructiveText = " + rgba_call(style["destructiveText"]) + ";",
           "",
           "/// One design-space rectangle (design px).",
           "struct CalypsoF33GenRect { int x; int y; int w; int h; };",
           "",
           "/// The complete F33.Abandon confirmation layout for one class.",
           "struct CalypsoF33GenLayout",
           "{",
           TAB + "int designWidth;",
           TAB + "int designHeight;",
           TAB + "CalypsoF33GenRect window;",
           TAB + "CalypsoF33GenRect status;",
           TAB + "CalypsoF33GenRect warning;",
           TAB + "CalypsoF33GenRect title;",
           TAB + "CalypsoF33GenRect message;",
           TAB + "CalypsoF33GenRect footer;",
           TAB + "CalypsoF33GenRect yes;",
           TAB + "CalypsoF33GenRect no;",
           "};",
           "",
           "inline constexpr CalypsoF33GenLayout kLayouts[] =",
           "{",
           ]
    for name in ("wide", "compact"):
        l = layouts[name]
        out.append(TAB + "// " + name)
        out.append(TAB + "{ " + str(l["designWidth"]) + ", " + str(l["designHeight"]) + ", "
                   + f33_rect(l, "window") + ", " + f33_rect(l, "status") + ", "
                   + f33_rect(l, "warning") + ", " + f33_rect(l, "title") + ", "
                   + f33_rect(l, "message") + ", " + f33_rect(l, "footer") + ", "
                   + f33_rect(l, "yes") + ", "
                   + f33_rect(l, "no") + " },")
    out.append("};")
    out.append("inline constexpr int kLayoutCount = " + str(len(layouts)) + ";")
    out.append("")
    out.append("/// Layout for a design canvas, or nullptr (the harness never guesses).")
    out.append("inline const CalypsoF33GenLayout* layoutForDesign(int dw, int dh)")
    out.append("{")
    out.append(TAB + "for (int i = 0; i < kLayoutCount; ++i)")
    out.append(TAB + TAB + "if (kLayouts[i].designWidth == dw && kLayouts[i].designHeight == dh)")
    out.append(TAB + TAB + TAB + "return &kLayouts[i];")
    out.append(TAB + "return nullptr;")
    out.append("}")
    out.append("")
    out.append("// Opening motion (capture mode deterministic).")
    out.append("inline constexpr int kMotionDurationMs = " + str(int(m["durationMs"])) + ";")
    out.append("inline constexpr float kMotionScaleFrom = %.6ff;" % float(m["scaleFrom"]))
    out.append("inline constexpr bool kMotionDisabledInCapture = true;")
    out.append("} } }")
    return NL.join(out) + NL


def emit_small_confirmation_h(doc, rel, ns, prefix):
    """Emitter for generated modal forms sharing the canonical renderer."""
    layouts = doc["layouts"]
    form = doc["form"]
    copy = doc["copy"]
    style = doc["style"]
    m = doc["motion"]
    button_ids = [b["id"] for b in form["buttons"]]
    out = [HEADER_BANNER,
           "// Canonical source: src/Calypso/Contracts/" + rel,
           "#pragma once",
           "#include <cstdint>",
           "namespace OpenXcom { namespace Calypso { namespace " + ns + " {",
           'inline constexpr const char* kContractVersion = "' + doc["version"] + '";',
           'inline constexpr const char* kFormId = "' + form["id"] + '";',
           "inline constexpr int kFamilyId = " + str(form["familyId"]) + ";",
           'inline constexpr const char* kArchetype = "' + form["archetype"] + '";',
           'inline constexpr const char* kSourceConfig = "' + form["source"] + '";']
    if form["archetype"] == "contact-decision":
        out += [
            'inline constexpr const char* kProtocol = ' + json.dumps(copy["protocol"], ensure_ascii=False) + ';',
        ]
    out.append("")
    presentation = doc.get("presentation") or {
        "density": "standard", "scaleNumerator": 1, "scaleDenominator": 1}
    out += ['inline constexpr const char* kDensityProfile = "' + presentation["density"] + '";',
            "inline constexpr int kPresentationScaleNumerator = " + str(presentation["scaleNumerator"]) + ";",
            "inline constexpr int kPresentationScaleDenominator = " + str(presentation["scaleDenominator"]) + ";",
            "inline constexpr float kPresentationScale = %.6ff;" % (
                float(presentation["scaleNumerator"]) / float(presentation["scaleDenominator"])),
            ""]
    out += ["struct " + prefix + "GenButton { const char* id; const char* label; const char* tone; const char* action; std::uint32_t fill; std::uint32_t border; std::uint32_t text; };",
            "inline constexpr " + prefix + "GenButton kButtons[] = {"]
    for b in form["buttons"]:
        out.append('    { "' + b["id"] + '", "' + b["label"] + '", "' + b["tone"] + '", "' + b["action"] + '", ' + rgba_call(b["style"]["fill"]) + ', ' + rgba_call(b["style"]["border"]) + ', ' + rgba_call(b["style"]["text"]) + ' },')
    out += ["};", "inline constexpr int kButtonCount = " + str(len(form["buttons"])) + ";", ""]
    out.append("inline constexpr float kCutCornerPx = %.6ff;" % float(style["cutCornerPx"]))
    out.append("inline constexpr float kProtocolTextInsetPx = %.6ff;" % float(style["protocolTextInsetPx"]))
    for key in ("panelFillTop","panelFillBottom","frame","protocolText","divider","footerFill","footerDot","warning"):
        out.append("inline constexpr std::uint32_t k" + key[0].upper() + key[1:] + " = " + rgba_call(style[key]) + ";")
    out.append("")
    wide_keys = [k for k,v in layouts["wide"].items() if isinstance(v, dict) and "x" in v]
    shell_parts = ["window","status","warning","title","message","footer"]
    table_parts = [k for k in wide_keys if k not in shell_parts and k != "buttons" and k not in button_ids and k not in ("no","yes")]
    out.append("struct " + prefix + "GenRect { int x; int y; int w; int h; };")
    out.append("struct " + prefix + "GenLayout { int designWidth; int designHeight; " + prefix + "GenRect window; " + prefix + "GenRect status; " + prefix + "GenRect warning; " + prefix + "GenRect title; " + prefix + "GenRect message; " + prefix + "GenRect footer;")
    for tp in sorted(table_parts):
        out.append("    " + prefix + "GenRect " + tp + ";")
    out.append("};")
    out.append("inline constexpr " + prefix + "GenLayout kLayouts[] = {")
    for name in ("wide","compact"):
        l = layouts[name]
        vals = [str(l["designWidth"]), str(l["designHeight"]),
                "{ " + str(l["window"]["x"]) + ", " + str(l["window"]["y"]) + ", " + str(l["window"]["width"]) + ", " + str(l["window"]["height"]) + " }",
                "{ " + str(l["status"]["x"]) + ", " + str(l["status"]["y"]) + ", " + str(l["status"]["width"]) + ", " + str(l["status"]["height"]) + " }",
                "{ " + str(l["warning"]["x"]) + ", " + str(l["warning"]["y"]) + ", " + str(l["warning"]["width"]) + ", " + str(l["warning"]["height"]) + " }",
                "{ " + str(l["title"]["x"]) + ", " + str(l["title"]["y"]) + ", " + str(l["title"]["width"]) + ", " + str(l["title"]["height"]) + " }",
                "{ " + str(l["message"]["x"]) + ", " + str(l["message"]["y"]) + ", " + str(l["message"]["width"]) + ", " + str(l["message"]["height"]) + " }",
                "{ " + str(l["footer"]["x"]) + ", " + str(l["footer"]["y"]) + ", " + str(l["footer"]["width"]) + ", " + str(l["footer"]["height"]) + " }"]
        for tp in sorted(table_parts):
            r = l.get(tp)
            if r:
                vals.append("{ " + str(r["x"]) + ", " + str(r["y"]) + ", " + str(r["width"]) + ", " + str(r["height"]) + " }")
            else:
                vals.append("{ 0, 0, 0, 0 }")
        out.append("    { " + ", ".join(vals) + " }, // " + name)
    out.append("};")
    out.append("struct " + prefix + "GenButtonRect { const char* id; " + prefix + "GenRect rect; };")
    out.append("inline constexpr " + prefix + "GenButtonRect kButtonRects[][ " + str(len(button_ids)) + " ] = {")
    for name in ("wide","compact"):
        l = layouts[name]
        row = []
        for bid in button_ids:
            rr = l["buttons"][bid]
            row.append('{ "' + bid + '", { ' + str(rr["x"]) + ", " + str(rr["y"]) + ", " + str(rr["width"]) + ", " + str(rr["height"]) + " } }")
        out.append("    { " + ", ".join(row) + " }, // " + name)
    out.append("};")
    out.append("inline constexpr int kLayoutCount = 2;")
    out.append("inline constexpr int kMotionDurationMs = " + str(int(m["durationMs"])) + ";")
    out.append("inline constexpr float kMotionScaleFrom = %.6ff;" % float(m["scaleFrom"]))
    out.append("inline const " + prefix + "GenLayout* layoutForDesign(int dw, int dh)")
    out.append("{")
    out.append("	for (int i = 0; i < kLayoutCount; ++i)")
    out.append("		if (kLayouts[i].designWidth == dw && kLayouts[i].designHeight == dh)")
    out.append("			return &kLayouts[i];")
    out.append("	return nullptr;")
    out.append("}")
    out.append("} } }")
    return NL.join(out) + NL

def emit_family_h(doc, rel, ns, prefix, profile):
    """Generic F21-family emitter: one rect member per declared part."""
    layouts = doc["layouts"]
    m = doc["motion"]
    parts = doc["parts"]
    out = [HEADER_BANNER,
           "// Canonical source: src/Calypso/Contracts/" + rel,
           "#pragma once",
           "#include <cstdint>",
           "namespace OpenXcom { namespace Calypso { namespace " + ns + " {",
           'inline constexpr const char* kContractVersion = "' + doc["version"] + '";',
           "",
           "/// One design-space rectangle (design px).",
           "struct " + prefix + "GenRect { int x; int y; int w; int h; };",
           "",
           "/// The complete " + rel + " layout for one class.",
           "struct " + prefix + "GenLayout",
           "{",
           TAB + "int designWidth;",
           TAB + "int designHeight;"]
    for p in parts:
        out.append(TAB + prefix + "GenRect " + p + ";")
    out += ["};",
            "",
            "inline constexpr " + prefix + "GenLayout kLayouts[] =",
            "{"]
    for name in ("wide", "compact"):
        l = layouts[name]
        out.append(TAB + "// " + name)
        out.append(TAB + "{ " + str(l["designWidth"]) + ", " + str(l["designHeight"]) + ", "
                   + ", ".join("{ " + str(l[p]["x"]) + ", " + str(l[p]["y"]) + ", "
                               + str(l[p]["width"]) + ", " + str(l[p]["height"]) + " }" for p in parts) + " },")
    out += ["};",
            "inline constexpr int kLayoutCount = " + str(len(layouts)) + ";",
            ""]
    if profile == "content-block":
        content = doc["content"]
        metrics = doc["metrics"]
        style = doc["style"]
        out += ["// Titleless content-block policy and measured layout metadata.",
                "inline constexpr bool kLegacyFallback = false;",
                "inline constexpr bool kFitFailureException = true;",
                "inline constexpr std::uint32_t kPanelFillTopRgba = 0x" + style["panelFillTop"].upper() + "u;",
                "inline constexpr std::uint32_t kPanelFillBottomRgba = 0x" + style["panelFillBottom"].upper() + "u;",
                "inline constexpr std::uint32_t kFrameRgba = 0x" + style["frame"].upper() + "u;",
                "inline constexpr std::uint32_t kDividerRgba = 0x" + style["divider"].upper() + "u;",
                "inline constexpr std::uint32_t kTextRgba = 0x" + style["text"].upper() + "u;",
                "inline constexpr int kCutCornerPx = " + str(style["cutCornerPx"]) + ";",
                "inline constexpr int kBorderWidthPx = " + str(style["borderWidthPx"]) + ";"]
        if content["kind"] == "table":
            cell_parts = [part for part in parts if part.startswith("cellR")]
            out += ["inline constexpr int kContentColumns = " + str(content["columns"]) + ";",
                    "inline constexpr int kContentRows = " + str(len(content["rows"])) + ";"]
            for layout_name, label in (("wide", "Wide"), ("compact", "Compact")):
                layout_metrics = metrics[layout_name]
                out.append("inline constexpr int k" + label + "GuardedLineHeight = "
                           + str(layout_metrics["guardedLineHeight"]) + ";")
                out.append("inline constexpr int k" + label + "LineCounts[] = { "
                           + ", ".join(str(layout_metrics["lineCounts"][part])
                                       for part in cell_parts) + " };")
        else:
            for layout_name, label in (("wide", "Wide"), ("compact", "Compact")):
                layout_metrics = metrics[layout_name]
                out.append("inline constexpr int k" + label + "GuardedLineHeight = "
                           + str(layout_metrics["guardedLineHeight"]) + ";")
                out.append("inline constexpr int k" + label + "TextLineCount = "
                           + str(layout_metrics["lineCount"]) + ";")
        out.append("")
    calibration = doc.get("engineTextScale")
    if calibration:
        out += ["// Physical Engine-TTF calibration against the CSS reference cap height.",
                "inline constexpr float kEngineTextScaleTitle = %.6ff;" % float(calibration["title"]),
                "inline constexpr float kEngineTextScaleData = %.6ff;" % float(calibration["data"]),
                "inline constexpr float kEngineTextScaleBody = %.6ff;" % float(calibration["body"]),
                "inline constexpr float kEngineTextScaleInput = %.6ff;" % float(calibration["input"]),
                "inline constexpr float kEngineTextScaleAction = %.6ff;" % float(calibration["action"]),
                ""]
    out += [
            "/// Layout for a design canvas, or nullptr (the harness never guesses).",
            "inline const " + prefix + "GenLayout* layoutForDesign(int dw, int dh)",
            "{",
            TAB + "for (int i = 0; i < kLayoutCount; ++i)",
            TAB + TAB + "if (kLayouts[i].designWidth == dw && kLayouts[i].designHeight == dh)",
            TAB + TAB + TAB + "return &kLayouts[i];",
            TAB + "return nullptr;",
            "}",
            "",
            "// Opening motion (capture mode deterministic).",
            "inline constexpr int kMotionDurationMs = " + str(int(m["durationMs"])) + ";",
            "inline constexpr float kMotionScaleFrom = %.6ff;" % float(m["scaleFrom"]),
            "inline constexpr bool kMotionDisabledInCapture = true;",
            "} } }"]
    return NL.join(out) + NL


def emit_screen_h(doc, rel, ns, prefix):
    """Emit typed screen/action layout data without reconstructing semantics."""
    cpp_string = lambda value: json.dumps(value, ensure_ascii=False)
    fixture_labels = doc["fixture"]["labels"]
    out = [HEADER_BANNER,
           "// Canonical source: src/Calypso/Contracts/" + rel,
           "#pragma once",
           "namespace OpenXcom { namespace Calypso { namespace " + ns + " {",
           'inline constexpr const char* kContractVersion = "' + doc["version"] + '";',
           'inline constexpr const char* kScreenId = "' + doc["screen"]["id"] + '";',
           'inline constexpr const char* kArchetype = "' + doc["screen"]["archetype"] + '";',
           "inline constexpr bool kProductionHook = "
           + ("true" if doc["screen"]["productionHook"] else "false") + ";",
           "inline constexpr const char* kSelectedSpeed = "
           + cpp_string(str((doc.get("fixture") or {}).get("selectedSpeed", ""))) + ";",
           "",
           "struct " + prefix + "GenRect { int x; int y; int w; int h; };",
           "struct " + prefix + "GenNamedRect",
           "{",
           TAB + "const char* id;",
           TAB + prefix + "GenRect rect;",
           "};",
           "struct " + prefix + "GenActionLayout",
           "{",
           TAB + "const char* id;",
           TAB + "const char* label;",
           TAB + "const char* component;",
           TAB + "const char* slotRole;",
           TAB + "const char* coordinateSpace;",
           TAB + prefix + "GenRect visible;",
           TAB + prefix + "GenRect hit;",
           TAB + "int focusOrder;",
           TAB + "int zOrder;",
           "};",
           "struct " + prefix + "GenLayout",
           "{",
           TAB + "int designWidth;",
           TAB + "int designHeight;",
           TAB + "const " + prefix + "GenActionLayout* actions;",
           TAB + "int actionCount;",
           TAB + "const " + prefix + "GenNamedRect* regions;",
           TAB + "int regionCount;",
           "};",
           "struct " + prefix + "GenFixtureCopy",
           "{",
           TAB + "const char* key;",
           TAB + "const char* value;",
           "};",
           ""]
    arrays = []
    for layout_name, label in (("wide", "Wide"), ("compact", "Compact")):
        layout = doc["layouts"][layout_name]
        array_name = "k" + label + "Actions"
        region_array_name = "k" + label + "Regions"
        arrays.append((array_name, region_array_name, layout))
        out += ["inline constexpr " + prefix + "GenNamedRect " + region_array_name + "[] =", "{"]
        for region_id, rect in layout["regions"].items():
            out.append(TAB + "{ " + cpp_string(region_id) + ", { "
                       + ", ".join(str(value) for value in rect) + " } },")
        out += ["};", ""]
        out += ["inline constexpr " + prefix + "GenActionLayout " + array_name + "[] =", "{"]
        for action in doc["actions"]:
            resolved = layout["actions"][action["id"]]
            visible = resolved["visibleRect"]
            hit = resolved["hitRect"]
            focus = resolved.get("focusOrder")
            out.append(TAB + "{ " + cpp_string(action["id"]) + ", "
                       + cpp_string(fixture_labels["actions"][action["id"]]) + ", "
                       + cpp_string(action["component"]) + ", "
                       + cpp_string(action["slotRole"]) + ", "
                       + cpp_string(resolved.get("coordinateSpace", "screen")) + ", { "
                       + ", ".join(str(value) for value in visible) + " }, { "
                       + ", ".join(str(value) for value in hit) + " }, "
                       + str(focus if isinstance(focus, int) else -1) + ", "
                       + str(resolved.get("zOrder", 1)) + " },")
        out += ["};", ""]
    out += ["inline constexpr " + prefix + "GenLayout kLayouts[] =", "{"]
    for array_name, region_array_name, layout in arrays:
        design = layout["designSize"]
        out.append(TAB + "{ " + str(design[0]) + ", " + str(design[1]) + ", "
                   + array_name + ", " + str(len(doc["actions"])) + ", "
                   + region_array_name + ", " + str(len(layout["regions"])) + " },")
    out += ["};",
            "inline constexpr int kLayoutCount = 2;",
            "",
            "inline constexpr " + prefix + "GenFixtureCopy kFixtureCopy[] =",
            "{"]
    for key, value in fixture_labels["copy"].items():
        out.append(TAB + "{ " + cpp_string(key) + ", " + cpp_string(value) + " },")
    out += ["};",
            "inline constexpr int kFixtureCopyCount = " + str(len(fixture_labels["copy"])) + ";",
            "",
            "inline const " + prefix + "GenLayout* layoutForDesign(int width, int height)",
            "{",
            TAB + "for (int index = 0; index < kLayoutCount; ++index)",
            TAB + TAB + "if (kLayouts[index].designWidth == width && kLayouts[index].designHeight == height)",
            TAB + TAB + TAB + "return &kLayouts[index];",
            TAB + "return nullptr;",
            "}",
            "} } }"]
    return NL.join(out) + NL


def emit_js(rel, obj, gname):
    body = json.dumps(obj, indent=2, sort_keys=True)
    return ("// AUTO-GENERATED by tools/generate-hd-ui-contracts.py -- DO NOT EDIT." + NL
            + "// Canonical source: src/Calypso/Contracts/" + rel + NL
            + "// Shared semantic object consumed by the clean harness and the DOM" + NL
            + "// reference builder (F33-PARITY-006: one contract, both consumers)." + NL
            + "globalThis." + gname + " = " + body + ";" + NL)


def ensure_generated_dir():
    os.makedirs(GENERATED_DIR, exist_ok=True)


def main(argv):
    parser = argparse.ArgumentParser(description="generate HD UI contracts")
    parser.add_argument("--check", action="store_true",
                        help="validate + compare without writing; exit 1 on stale output")
    parser.add_argument("--web-output", default=None,
                        help="directory (relative to CWD) for the generated DOM modules")
    parser.add_argument("--registry", default=REGISTRY_PATH,
                        help="canonical contract registry (default: " + REGISTRY_REL + ")")
    args = parser.parse_args(argv)

    registry_path = args.registry if os.path.isabs(args.registry) else os.path.join(os.getcwd(), args.registry)
    entries = validate_registry(load_registry(registry_path))
    docs = []
    for entry in entries:
        rel = entry["contract"]
        doc = load_json(rel)
        if entry["emitter"] == "theme":
            validate_theme(doc)
        elif entry["emitter"] == "legacy-abandon":
            validate_f33(doc)
        elif entry["emitter"] == "screen":
            validate_screen(doc, rel)
        else:
            validate_family(doc, rel, entry["validationProfile"],
                            entry.get("engineTextCalibration", False))
        docs.append((entry, doc))
    versions = [(entry["contract"], doc["version"]) for entry, doc in docs]
    for rel, ver in versions[1:]:
        if ver != versions[0][1]:
            fail("contract versions diverge: " + versions[0][0] + " " + versions[0][1]
                 + " vs " + rel + " " + ver)

    # Directory creation happens ONLY on the write path -- --check performs
    # no writes at all (normative rule, generator docstring).
    outputs = []
    web = None
    if args.web_output:
        web = args.web_output if os.path.isabs(args.web_output) else os.path.join(os.getcwd(), args.web_output)
    for entry, doc in docs:
        rel = entry["contract"]
        native = entry["native"]
        if entry["emitter"] == "theme":
            native_text = emit_theme_h(doc)
        elif entry["emitter"] == "legacy-abandon":
            native_text = emit_f33_h(doc)
        elif entry["emitter"] == "screen":
            native_text = emit_screen_h(
                doc, rel, native["namespace"], native["prefix"])
        elif entry["validationProfile"] in {"small-confirmation", "contact-decision"}:
            native_text = emit_small_confirmation_h(
                doc, rel, native["namespace"], native["prefix"])
        else:
            native_text = emit_family_h(
                doc, rel, native["namespace"], native["prefix"], entry["validationProfile"])
        outputs.append((os.path.join(GENERATED_DIR, native["output"]), native_text))
        if web is not None:
            browser = entry["browser"]
            outputs.append((os.path.join(web, browser["output"]),
                            emit_js(rel, doc, browser["global"])))

    if args.check:
        changed = []
        for path, text in outputs:
            current = None
            if os.path.isfile(path):
                with open(path, "r", encoding="utf-8") as f:
                    current = f.read()
            if current != text:
                changed.append(path)
        if changed:
            for path in changed:
                print("generate-hd-ui-contracts: STALE: " + path)
            print("generate-hd-ui-contracts: run without --check to regenerate; never hand-edit generated consumers")
            return 1
        print("generate-hd-ui-contracts: all " + str(len(outputs)) + " consumers are current")
        return 0

    ensure_generated_dir()
    if web is not None:
        os.makedirs(web, exist_ok=True)
    for path, text in outputs:
        tmp = path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            f.write(text)
        os.replace(tmp, path)
    print("generate-hd-ui-contracts: wrote " + str(len(outputs)) + " generated consumers")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
