#!/usr/bin/env python3
"""
generate-hd-ui-contracts.py -- Phase 46.4-F33 canonical engine/DOM contract
generator (docs/phases/phase-46.4-f33-engine-dom-visual-parity.md, 46.4-F33.2).

One canonical JSON source per contract (kept in the engine repo so the fork can
validate them independently) produces TWO checked consumers:

    src/Calypso/Contracts/hd-ui-theme.json     -> src/Calypso/Generated/CalypsoHdTheme.generated.h
                                                  <web-output>/hd-ui-theme.js
    src/Calypso/Contracts/f33-abandon.json     -> src/Calypso/Generated/CalypsoF33Abandon.generated.h
                                                  <web-output>/f33-abandon.js

Rules (normative):
  * output is DETERMINISTIC across supported build hosts (stable ordering, no
    timestamps, fixed float formatting);
  * engine paths resolve RELATIVE TO THIS SCRIPT; --web-output is relative to
    the CURRENT WORKING DIRECTORY (the parent repo root when invoked from CI);
  * --check performs no writes at all and exits 1 with a focused diff when any
    generated consumer is stale (drift detection for F33-PARITY-006);
  * the schema is validated before generation: version required, colours in
    RRGGBBAA, integer rects, compact action targets >= 44x44, sane motion;
  * hand-editing any generated file is forbidden -- edit the JSON instead.

Run from the parent repository root:
    python3 engine/oxce/tools/generate-hd-ui-contracts.py --web-output web/public/generated
    python3 engine/oxce/tools/generate-hd-ui-contracts.py --check --web-output web/public/generated
"""

import argparse
import json
import os
import re
import sys

NL = chr(10)          # newline
TAB = chr(9)          # tab

ENGINE_TOOLS = os.path.dirname(os.path.abspath(__file__))
CALYPSO_DIR = os.path.normpath(os.path.join(ENGINE_TOOLS, "..", "src", "Calypso"))
CONTRACTS_DIR = os.path.join(CALYPSO_DIR, "Contracts")
GENERATED_DIR = os.path.join(CALYPSO_DIR, "Generated")

HEADER_BANNER = "// AUTO-GENERATED by tools/generate-hd-ui-contracts.py -- DO NOT EDIT." + NL
MIN_ACTION_TARGET = 44


def fail(msg):
    print("generate-hd-ui-contracts: error: " + msg, file=sys.stderr)
    sys.exit(1)


def load_json(rel):
    path = os.path.join(CONTRACTS_DIR, rel)
    if not os.path.isfile(path):
        fail("canonical contract missing: " + path)
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


import re as _re

VERSION_RE = _re.compile(r"^[A-Za-z0-9._-]+$")


def validate_theme(theme):
    if theme.get("schema") != 1:
        fail("hd-ui-theme.json: schema must be 1")
    if not isinstance(theme.get("version"), str) or not VERSION_RE.match(theme.get("version", "")):
        fail("hd-ui-theme.json: version string required (^[A-Za-z0-9._-]+$)")
    colors = theme.get("colors")
    if not isinstance(colors, dict) or not colors:
        fail("hd-ui-theme.json: colors object required")
    for name, value in colors.items():
        if not isinstance(value, str) or not re.fullmatch(r"[0-9A-Fa-f]{8}", value):
            fail("hd-ui-theme.json: color " + name + " must be packed RRGGBBAA")
    dlg = theme.get("dialog") or {}
    if dlg.get("radiusPx", 0) <= 0 or dlg.get("borderWidthPx", 0) <= 0:
        fail("hd-ui-theme.json: dialog.radiusPx/borderWidthPx must be > 0")
    shadow = theme.get("shadow") or {}
    halo = theme.get("halo") or {}
    if shadow.get("glowRadiusPx", 0) <= 0 or halo.get("glowRadiusPx", 0) <= 0:
        fail("hd-ui-theme.json: shadow/halo glowRadiusPx must be > 0")
    typography = theme.get("typography") or {}
    for key in ("titleFontSizeScale", "bodyFontSizeScale", "bodyLineHeight",
                "labelFontSizeScaleWide", "labelFontSizeScaleCompact",
                "bodyFontSizeScaleWide", "bodyFontSizeScaleCompact",
                "bodyFontWidthScaleWide", "bodyFontWidthScaleCompact"):
        if not isinstance(typography.get(key), (int, float)) or typography[key] <= 0:
            fail("hd-ui-theme.json: typography." + key + " must be > 0")
    for key in ("labelFontSizePx", "bodyFontSizePx", "titleFontWeight", "labelFontWeight", "bodyFontWeight"):
        if not isinstance(typography.get(key), int) or typography[key] <= 0:
            fail("hd-ui-theme.json: typography." + key + " must be a positive integer")


def validate_f33(f33):
    if f33.get("schema") != 1:
        fail("f33-abandon.json: schema must be 1")
    if not isinstance(f33.get("version"), str) or not f33["version"]:
        fail("f33-abandon.json: version string required")
    layouts = f33.get("layouts")
    if not isinstance(layouts, dict) or "wide" not in layouts or "compact" not in layouts:
        fail("f33-abandon.json: explicit wide/compact layouts required")
    for name in ("wide", "compact"):
        l = layouts[name]
        if l.get("designWidth", 0) <= 0 or l.get("designHeight", 0) <= 0:
            fail("f33-abandon.json: " + name + " design canvas required")
        for part in ("window", "title", "message", "yes", "no"):
            r = l.get(part)
            if not r or not all(isinstance(r[k], int) for k in ("x", "y", "width", "height")):
                fail("f33-abandon.json: " + name + "." + part + " must be an integer rect")
        for part in ("yes", "no"):
            if l[part]["width"] < MIN_ACTION_TARGET or l[part]["height"] < MIN_ACTION_TARGET:
                fail("f33-abandon.json: " + name + "." + part
                     + " below the " + str(MIN_ACTION_TARGET) + "x" + str(MIN_ACTION_TARGET)
                     + " action-target floor")

        def contained(inner, outer):
            return (inner["x"] >= outer["x"] and inner["y"] >= outer["y"]
                    and inner["x"] + inner["width"] <= outer["x"] + outer["width"]
                    and inner["y"] + inner["height"] <= outer["y"] + outer["height"])
        if not contained(l["window"], {"x": 0, "y": 0, "width": l["designWidth"], "height": l["designHeight"]}):
            fail("f33-abandon.json: " + name + ".window must fit the design canvas")
        for part in ("title", "message", "yes", "no"):
            if not contained(l[part], l["window"]):
                fail("f33-abandon.json: " + name + "." + part + " must be inside the window")
        if (l["yes"]["x"] < l["no"]["x"] + l["no"]["width"] and l["no"]["x"] < l["yes"]["x"] + l["yes"]["width"]
                and l["yes"]["y"] < l["no"]["y"] + l["no"]["height"] and l["no"]["y"] < l["yes"]["y"] + l["yes"]["height"]):
            fail("f33-abandon.json: " + name + ".yes and .no must not overlap")
    m = f33.get("motion") or {}
    if m.get("durationMs", 0) <= 0 or m.get("durationMs", 0) > 1000:
        fail("f33-abandon.json: motion.durationMs must be in (0, 1000]")
    if not (0.0 < m.get("scaleFrom", 0.0) <= 1.0):
        fail("f33-abandon.json: motion.scaleFrom must be in (0, 1]")
    if m.get("captureModeDurationMs") != 0:
        fail("f33-abandon.json: captureModeDurationMs must be 0 (deterministic captures)")


def rgba_call(value):
    # Emit the packed 0xRRGGBBAA word directly: the generated header stays
    # dependency-free (no CalypsoHdUiModel.h include needed).
    return "0x%08Xu" % int(value, 16)


def emit_theme_h(theme):
    colors = theme["colors"]
    out = [HEADER_BANNER,
           "// Canonical source: src/Calypso/Contracts/hd-ui-theme.json",
           "#pragma once",
           "#include <cstdint>",
           "#include <cstring>",
           "namespace OpenXcom { namespace Calypso { namespace CalypsoHdThemeGen {",
           'inline constexpr const char* kContractVersion = "' + theme["version"] + '";',
           "",
           "// Semantic palette (0xRRGGBBAA).",
           ]
    for name in sorted(colors.keys()):
        const = "k" + name[0].upper() + name[1:]
        out.append("inline constexpr std::uint32_t " + const + " = " + rgba_call(colors[name]) + ";")
    out.append("")
    out.append("// Style parameters (design px).")
    out.append("inline constexpr float kDialogRadiusPx = %.6ff;" % float(theme["dialog"]["radiusPx"]))
    out.append("inline constexpr float kButtonRadiusPx = %.6ff;" % float(theme["button"]["radiusPx"]))
    out.append("inline constexpr float kBorderWidthPx = %.6ff;" % float(theme["dialog"]["borderWidthPx"]))
    out.append("inline constexpr float kTitleTrackingEm = %.6ff;" % float(theme["tracking"]["titleEm"]))
    out.append("inline constexpr float kLabelTrackingEm = %.6ff;" % float(theme["tracking"]["labelEm"]))
    out.append("inline constexpr float kShadowGlowRadiusPx = %.6ff;" % float(theme["shadow"]["glowRadiusPx"]))
    out.append("inline constexpr float kHaloGlowRadiusPx = %.6ff;" % float(theme["halo"]["glowRadiusPx"]))
    out.append("inline constexpr float kTitleFontSizeScale = %.6ff;" % float(theme["typography"]["titleFontSizeScale"]))
    out.append("inline constexpr float kBodyFontSizeScale = %.6ff;" % float(theme["typography"]["bodyFontSizeScale"]))
    out.append("inline constexpr int kLabelFontSizePx = %d;" % int(theme["typography"]["labelFontSizePx"]))
    out.append("inline constexpr float kLabelFontSizeScaleWide = %.6ff;" % float(theme["typography"]["labelFontSizeScaleWide"]))
    out.append("inline constexpr float kLabelFontSizeScaleCompact = %.6ff;" % float(theme["typography"]["labelFontSizeScaleCompact"]))
    out.append("inline constexpr int kBodyFontSizePx = %d;" % int(theme["typography"]["bodyFontSizePx"]))
    out.append("inline constexpr float kBodyFontSizeScaleWide = %.6ff;" % float(theme["typography"]["bodyFontSizeScaleWide"]))
    out.append("inline constexpr float kBodyFontSizeScaleCompact = %.6ff;" % float(theme["typography"]["bodyFontSizeScaleCompact"]))
    out.append("inline constexpr float kBodyFontWidthScaleWide = %.6ff;" % float(theme["typography"]["bodyFontWidthScaleWide"]))
    out.append("inline constexpr float kBodyFontWidthScaleCompact = %.6ff;" % float(theme["typography"]["bodyFontWidthScaleCompact"]))
    out.append("inline constexpr float kBodyLineHeight = %.6ff;" % float(theme["typography"]["bodyLineHeight"]))
    out.append("inline constexpr int kTitleFontWeight = %d;" % int(theme["typography"]["titleFontWeight"]))
    out.append("inline constexpr int kLabelFontWeight = %d;" % int(theme["typography"]["labelFontWeight"]))
    out.append("inline constexpr int kBodyFontWeight = %d;" % int(theme["typography"]["bodyFontWeight"]))
    out.append("")
    out.append("// Semantic token key strings for the interaction-state mapping")
    out.append("// (CalypsoHdInteractionState.h) -- values above, keys here.")
    names = sorted(colors.keys())
    for name in names:
        token = "token.color." + name
        const = "kToken" + name[0].upper() + name[1:]
        out.append('inline constexpr const char* ' + const + ' = "' + token + '";')
    out.append("")
    out.append("/// Resolve a semantic token key to its packed RGBA value (0 for")
    out.append("/// unknown keys). Generated table; one source of truth.")
    out.append("inline std::uint32_t calypsoHdThemeColorForToken(const char* token)")
    out.append("{")
    out.append(TAB + "struct Entry { const char* key; std::uint32_t value; };")
    out.append(TAB + "static constexpr Entry kEntries[] = {")
    for name in names:
        const = "k" + name[0].upper() + name[1:]
        tconst = "kToken" + name[0].upper() + name[1:]
        out.append(TAB + TAB + "{ " + tconst + ", " + const + " },")
    out.append(TAB + "};")
    out.append(TAB + "for (const Entry& e : kEntries)")
    out.append(TAB + TAB + "if (std::strcmp(token, e.key) == 0) return e.value;")
    out.append(TAB + "return 0;")
    out.append("}")
    out.append("} } }")
    return NL.join(out) + NL


def f33_rect(l, part):
    r = l[part]
    return "{ " + str(r["x"]) + ", " + str(r["y"]) + ", " + str(r["width"]) + ", " + str(r["height"]) + " }"


def emit_f33_h(f33):
    layouts = f33["layouts"]
    m = f33["motion"]
    out = [HEADER_BANNER,
           "// Canonical source: src/Calypso/Contracts/f33-abandon.json",
           "#pragma once",
           "#include <cstdint>",
           "namespace OpenXcom { namespace Calypso { namespace CalypsoF33AbandonGen {",
           'inline constexpr const char* kContractVersion = "' + f33["version"] + '";',
           "",
           "/// One design-space rectangle (design px).",
           "struct CalypsoF33GenRect { int x; int y; int w; int h; };",
           "",
           "/// The complete F33.Abandon confirmation layout for one class.",
           "struct CalypsoF33GenLayout",
           "{",
           TAB + "int designWidth;",
           TAB + "int designHeight;",
           TAB + "CalypsoF33GenRect window;",
           TAB + "CalypsoF33GenRect title;",
           TAB + "CalypsoF33GenRect message;",
           TAB + "CalypsoF33GenRect yes;",
           TAB + "CalypsoF33GenRect no;",
           "};",
           "",
           "inline constexpr CalypsoF33GenLayout kLayouts[] =",
           "{",
           ]
    for name in ("wide", "compact"):
        l = layouts[name]
        out.append(TAB + "// " + name)
        out.append(TAB + "{ " + str(l["designWidth"]) + ", " + str(l["designHeight"]) + ", "
                   + f33_rect(l, "window") + ", " + f33_rect(l, "title") + ", "
                   + f33_rect(l, "message") + ", " + f33_rect(l, "yes") + ", "
                   + f33_rect(l, "no") + " },")
    out.append("};")
    out.append("inline constexpr int kLayoutCount = " + str(len(layouts)) + ";")
    out.append("")
    out.append("/// Layout for a design canvas, or nullptr (the harness never guesses).")
    out.append("inline const CalypsoF33GenLayout* layoutForDesign(int dw, int dh)")
    out.append("{")
    out.append(TAB + "for (int i = 0; i < kLayoutCount; ++i)")
    out.append(TAB + TAB + "if (kLayouts[i].designWidth == dw && kLayouts[i].designHeight == dh)")
    out.append(TAB + TAB + TAB + "return &kLayouts[i];")
    out.append(TAB + "return nullptr;")
    out.append("}")
    out.append("")
    out.append("// Opening motion (capture mode deterministic).")
    out.append("inline constexpr int kMotionDurationMs = " + str(int(m["durationMs"])) + ";")
    out.append("inline constexpr float kMotionScaleFrom = %.6ff;" % float(m["scaleFrom"]))
    out.append("inline constexpr bool kMotionDisabledInCapture = true;")
    out.append("} } }")
    return NL.join(out) + NL


def emit_js(rel, obj, gname):
    body = json.dumps(obj, indent=2, sort_keys=True)
    return ("// AUTO-GENERATED by tools/generate-hd-ui-contracts.py -- DO NOT EDIT." + NL
            + "// Canonical source: src/Calypso/Contracts/" + rel + NL
            + "// Shared semantic object consumed by the clean harness and the DOM" + NL
            + "// reference builder (F33-PARITY-006: one contract, both consumers)." + NL
            + "globalThis." + gname + " = " + body + ";" + NL)


def ensure_generated_dir():
    os.makedirs(GENERATED_DIR, exist_ok=True)


def main(argv):
    parser = argparse.ArgumentParser(description="generate HD UI contracts")
    parser.add_argument("--check", action="store_true",
                        help="validate + compare without writing; exit 1 on stale output")
    parser.add_argument("--web-output", default=None,
                        help="directory (relative to CWD) for the generated DOM modules")
    args = parser.parse_args(argv)

    theme = load_json("hd-ui-theme.json")
    f33 = load_json("f33-abandon.json")
    validate_theme(theme)
    validate_f33(f33)
    if theme["version"] != f33["version"]:
        fail("contract versions diverge: " + theme["version"] + " vs " + f33["version"])

    theme_h = emit_theme_h(theme)
    f33_h = emit_f33_h(f33)
    theme_js = emit_js("hd-ui-theme.json", theme, "CalypsoHdTheme")
    f33_js = emit_js("f33-abandon.json", f33, "CalypsoF33Abandon")

    # Directory creation happens ONLY on the write path -- --check performs
    # no writes at all (normative rule, generator docstring).
    outputs = [
        (os.path.join(GENERATED_DIR, "CalypsoHdTheme.generated.h"), theme_h),
        (os.path.join(GENERATED_DIR, "CalypsoF33Abandon.generated.h"), f33_h),
    ]
    web = None
    if args.web_output:
        web = args.web_output if os.path.isabs(args.web_output) else os.path.join(os.getcwd(), args.web_output)
        outputs += [
            (os.path.join(web, "hd-ui-theme.js"), theme_js),
            (os.path.join(web, "f33-abandon.js"), f33_js),
        ]

    if args.check:
        changed = []
        for path, text in outputs:
            current = None
            if os.path.isfile(path):
                with open(path, "r", encoding="utf-8") as f:
                    current = f.read()
            if current != text:
                changed.append(path)
        if changed:
            for path in changed:
                print("generate-hd-ui-contracts: STALE: " + path)
            print("generate-hd-ui-contracts: run without --check to regenerate; never hand-edit generated consumers")
            return 1
        print("generate-hd-ui-contracts: all " + str(len(outputs)) + " consumers are current")
        return 0

    ensure_generated_dir()
    if web is not None:
        os.makedirs(web, exist_ok=True)
    for path, text in outputs:
        tmp = path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            f.write(text)
        os.replace(tmp, path)
    print("generate-hd-ui-contracts: wrote " + str(len(outputs)) + " generated consumers")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
